/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package EsquareEmployee_Slayer.model.impl;

import EsquareEmployee_Slayer.model.Employees;

import EsquareEmployee_Slayer.service.EmployeesLocalServiceUtil;

/**
 * The extended model base implementation for the Employees service. Represents a row in the &quot;esquare_Employees&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeesImpl
 * @see Employees
 * @generated
 */
public abstract class EmployeesBaseImpl
	extends EmployeesModelImpl implements Employees {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employees model instance should use the <code>Employees</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			EmployeesLocalServiceUtil.addEmployees(this);
		}
		else {
			EmployeesLocalServiceUtil.updateEmployees(this);
		}
	}

}