/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package EsquareEmployee_Slayer.model.impl;

import EsquareEmployee_Slayer.model.Employees;
import EsquareEmployee_Slayer.model.EmployeesModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Employees service. Represents a row in the &quot;esquare_Employees&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EmployeesModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeesImpl
 * @generated
 */
@JSON(strict = true)
public class EmployeesModelImpl
	extends BaseModelImpl<Employees> implements EmployeesModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employees model instance should use the <code>Employees</code> interface instead.
	 */
	public static final String TABLE_NAME = "esquare_Employees";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"employeeId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"employeeName", Types.VARCHAR},
		{"employeeMobileNumber", Types.VARCHAR},
		{"employeeDesignation", Types.VARCHAR},
		{"employeephoto", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("employeeName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("employeeMobileNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("employeeDesignation", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("employeephoto", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table esquare_Employees (uuid_ VARCHAR(75) null,employeeId LONG not null primary key,groupId LONG,companyId LONG,employeeName VARCHAR(75) null,employeeMobileNumber VARCHAR(75) null,employeeDesignation VARCHAR(75) null,employeephoto VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table esquare_Employees";

	public static final String ORDER_BY_JPQL =
		" ORDER BY employees.employeeId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY esquare_Employees.employeeId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMPLOYEEDESIGNATION_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMPLOYEEID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public EmployeesModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _employeeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEmployeeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _employeeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Employees.class;
	}

	@Override
	public String getModelClassName() {
		return Employees.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Employees, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Employees, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Employees, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Employees)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Employees, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Employees, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Employees)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Employees, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Employees, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Employees, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Employees, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Employees, Object>>();

			attributeGetterFunctions.put("uuid", Employees::getUuid);
			attributeGetterFunctions.put(
				"employeeId", Employees::getEmployeeId);
			attributeGetterFunctions.put("groupId", Employees::getGroupId);
			attributeGetterFunctions.put("companyId", Employees::getCompanyId);
			attributeGetterFunctions.put(
				"employeeName", Employees::getEmployeeName);
			attributeGetterFunctions.put(
				"employeeMobileNumber", Employees::getEmployeeMobileNumber);
			attributeGetterFunctions.put(
				"employeeDesignation", Employees::getEmployeeDesignation);
			attributeGetterFunctions.put(
				"employeephoto", Employees::getEmployeephoto);
			attributeGetterFunctions.put(
				"createDate", Employees::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Employees::getModifiedDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Employees, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Employees, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Employees, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Employees, String>)Employees::setUuid);
			attributeSetterBiConsumers.put(
				"employeeId",
				(BiConsumer<Employees, Long>)Employees::setEmployeeId);
			attributeSetterBiConsumers.put(
				"groupId", (BiConsumer<Employees, Long>)Employees::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<Employees, Long>)Employees::setCompanyId);
			attributeSetterBiConsumers.put(
				"employeeName",
				(BiConsumer<Employees, String>)Employees::setEmployeeName);
			attributeSetterBiConsumers.put(
				"employeeMobileNumber",
				(BiConsumer<Employees, String>)
					Employees::setEmployeeMobileNumber);
			attributeSetterBiConsumers.put(
				"employeeDesignation",
				(BiConsumer<Employees, String>)
					Employees::setEmployeeDesignation);
			attributeSetterBiConsumers.put(
				"employeephoto",
				(BiConsumer<Employees, String>)Employees::setEmployeephoto);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Employees, Date>)Employees::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Employees, Date>)Employees::setModifiedDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public String getEmployeeName() {
		if (_employeeName == null) {
			return "";
		}
		else {
			return _employeeName;
		}
	}

	@Override
	public void setEmployeeName(String employeeName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeName = employeeName;
	}

	@JSON
	@Override
	public String getEmployeeMobileNumber() {
		if (_employeeMobileNumber == null) {
			return "";
		}
		else {
			return _employeeMobileNumber;
		}
	}

	@Override
	public void setEmployeeMobileNumber(String employeeMobileNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeMobileNumber = employeeMobileNumber;
	}

	@JSON
	@Override
	public String getEmployeeDesignation() {
		if (_employeeDesignation == null) {
			return "";
		}
		else {
			return _employeeDesignation;
		}
	}

	@Override
	public void setEmployeeDesignation(String employeeDesignation) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeDesignation = employeeDesignation;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalEmployeeDesignation() {
		return getColumnOriginalValue("employeeDesignation");
	}

	@JSON
	@Override
	public String getEmployeephoto() {
		if (_employeephoto == null) {
			return "";
		}
		else {
			return _employeephoto;
		}
	}

	@Override
	public void setEmployeephoto(String employeephoto) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeephoto = employeephoto;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Employees.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Employees.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Employees toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Employees>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmployeesImpl employeesImpl = new EmployeesImpl();

		employeesImpl.setUuid(getUuid());
		employeesImpl.setEmployeeId(getEmployeeId());
		employeesImpl.setGroupId(getGroupId());
		employeesImpl.setCompanyId(getCompanyId());
		employeesImpl.setEmployeeName(getEmployeeName());
		employeesImpl.setEmployeeMobileNumber(getEmployeeMobileNumber());
		employeesImpl.setEmployeeDesignation(getEmployeeDesignation());
		employeesImpl.setEmployeephoto(getEmployeephoto());
		employeesImpl.setCreateDate(getCreateDate());
		employeesImpl.setModifiedDate(getModifiedDate());

		employeesImpl.resetOriginalValues();

		return employeesImpl;
	}

	@Override
	public Employees cloneWithOriginalValues() {
		EmployeesImpl employeesImpl = new EmployeesImpl();

		employeesImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		employeesImpl.setEmployeeId(
			this.<Long>getColumnOriginalValue("employeeId"));
		employeesImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		employeesImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		employeesImpl.setEmployeeName(
			this.<String>getColumnOriginalValue("employeeName"));
		employeesImpl.setEmployeeMobileNumber(
			this.<String>getColumnOriginalValue("employeeMobileNumber"));
		employeesImpl.setEmployeeDesignation(
			this.<String>getColumnOriginalValue("employeeDesignation"));
		employeesImpl.setEmployeephoto(
			this.<String>getColumnOriginalValue("employeephoto"));
		employeesImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		employeesImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));

		return employeesImpl;
	}

	@Override
	public int compareTo(Employees employees) {
		long primaryKey = employees.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Employees)) {
			return false;
		}

		Employees employees = (Employees)object;

		long primaryKey = employees.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Employees> toCacheModel() {
		EmployeesCacheModel employeesCacheModel = new EmployeesCacheModel();

		employeesCacheModel.uuid = getUuid();

		String uuid = employeesCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			employeesCacheModel.uuid = null;
		}

		employeesCacheModel.employeeId = getEmployeeId();

		employeesCacheModel.groupId = getGroupId();

		employeesCacheModel.companyId = getCompanyId();

		employeesCacheModel.employeeName = getEmployeeName();

		String employeeName = employeesCacheModel.employeeName;

		if ((employeeName != null) && (employeeName.length() == 0)) {
			employeesCacheModel.employeeName = null;
		}

		employeesCacheModel.employeeMobileNumber = getEmployeeMobileNumber();

		String employeeMobileNumber = employeesCacheModel.employeeMobileNumber;

		if ((employeeMobileNumber != null) &&
			(employeeMobileNumber.length() == 0)) {

			employeesCacheModel.employeeMobileNumber = null;
		}

		employeesCacheModel.employeeDesignation = getEmployeeDesignation();

		String employeeDesignation = employeesCacheModel.employeeDesignation;

		if ((employeeDesignation != null) &&
			(employeeDesignation.length() == 0)) {

			employeesCacheModel.employeeDesignation = null;
		}

		employeesCacheModel.employeephoto = getEmployeephoto();

		String employeephoto = employeesCacheModel.employeephoto;

		if ((employeephoto != null) && (employeephoto.length() == 0)) {
			employeesCacheModel.employeephoto = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			employeesCacheModel.createDate = createDate.getTime();
		}
		else {
			employeesCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			employeesCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			employeesCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return employeesCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Employees, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Employees, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Employees, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Employees)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Employees>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Employees.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _employeeId;
	private long _groupId;
	private long _companyId;
	private String _employeeName;
	private String _employeeMobileNumber;
	private String _employeeDesignation;
	private String _employeephoto;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Employees, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Employees)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("employeeId", _employeeId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("employeeName", _employeeName);
		_columnOriginalValues.put(
			"employeeMobileNumber", _employeeMobileNumber);
		_columnOriginalValues.put("employeeDesignation", _employeeDesignation);
		_columnOriginalValues.put("employeephoto", _employeephoto);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("employeeId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("employeeName", 16L);

		columnBitmasks.put("employeeMobileNumber", 32L);

		columnBitmasks.put("employeeDesignation", 64L);

		columnBitmasks.put("employeephoto", 128L);

		columnBitmasks.put("createDate", 256L);

		columnBitmasks.put("modifiedDate", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Employees _escapedModel;

}