/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.esq.bus.reservation.slayers.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AuditLog service. Represents a row in the &quot;BOOKRESERVATION_AuditLog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.esq.bus.reservation.slayers.model.impl.AuditLogModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.esq.bus.reservation.slayers.model.impl.AuditLogImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AuditLog
 * @generated
 */
@ProviderType
public interface AuditLogModel extends BaseModel<AuditLog> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a audit log model instance should use the {@link AuditLog} interface instead.
	 */

	/**
	 * Returns the primary key of this audit log.
	 *
	 * @return the primary key of this audit log
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this audit log.
	 *
	 * @param primaryKey the primary key of this audit log
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the audit ID of this audit log.
	 *
	 * @return the audit ID of this audit log
	 */
	public long getAuditId();

	/**
	 * Sets the audit ID of this audit log.
	 *
	 * @param auditId the audit ID of this audit log
	 */
	public void setAuditId(long auditId);

	/**
	 * Returns the entity name of this audit log.
	 *
	 * @return the entity name of this audit log
	 */
	@AutoEscape
	public String getEntityName();

	/**
	 * Sets the entity name of this audit log.
	 *
	 * @param entityName the entity name of this audit log
	 */
	public void setEntityName(String entityName);

	/**
	 * Returns the entity ID of this audit log.
	 *
	 * @return the entity ID of this audit log
	 */
	public long getEntityId();

	/**
	 * Sets the entity ID of this audit log.
	 *
	 * @param entityId the entity ID of this audit log
	 */
	public void setEntityId(long entityId);

	/**
	 * Returns the action of this audit log.
	 *
	 * @return the action of this audit log
	 */
	@AutoEscape
	public String getAction();

	/**
	 * Sets the action of this audit log.
	 *
	 * @param action the action of this audit log
	 */
	public void setAction(String action);

	/**
	 * Returns the user ID of this audit log.
	 *
	 * @return the user ID of this audit log
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this audit log.
	 *
	 * @param userId the user ID of this audit log
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this audit log.
	 *
	 * @return the user uuid of this audit log
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this audit log.
	 *
	 * @param userUuid the user uuid of this audit log
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the action date of this audit log.
	 *
	 * @return the action date of this audit log
	 */
	public Date getActionDate();

	/**
	 * Sets the action date of this audit log.
	 *
	 * @param actionDate the action date of this audit log
	 */
	public void setActionDate(Date actionDate);

	@Override
	public AuditLog cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}