/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.esq.bus.reservation.slayers.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Bus service. Represents a row in the &quot;BOOKRESERVATION_Bus&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.esq.bus.reservation.slayers.model.impl.BusModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.esq.bus.reservation.slayers.model.impl.BusImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Bus
 * @generated
 */
@ProviderType
public interface BusModel extends BaseModel<Bus> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bus model instance should use the {@link Bus} interface instead.
	 */

	/**
	 * Returns the primary key of this bus.
	 *
	 * @return the primary key of this bus
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bus.
	 *
	 * @param primaryKey the primary key of this bus
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the bus ID of this bus.
	 *
	 * @return the bus ID of this bus
	 */
	public long getBusId();

	/**
	 * Sets the bus ID of this bus.
	 *
	 * @param busId the bus ID of this bus
	 */
	public void setBusId(long busId);

	/**
	 * Returns the bus number of this bus.
	 *
	 * @return the bus number of this bus
	 */
	@AutoEscape
	public String getBusNumber();

	/**
	 * Sets the bus number of this bus.
	 *
	 * @param busNumber the bus number of this bus
	 */
	public void setBusNumber(String busNumber);

	/**
	 * Returns the bus plate number of this bus.
	 *
	 * @return the bus plate number of this bus
	 */
	@AutoEscape
	public String getBusPlateNumber();

	/**
	 * Sets the bus plate number of this bus.
	 *
	 * @param busPlateNumber the bus plate number of this bus
	 */
	public void setBusPlateNumber(String busPlateNumber);

	/**
	 * Returns the bus type of this bus.
	 *
	 * @return the bus type of this bus
	 */
	public int getBusType();

	/**
	 * Sets the bus type of this bus.
	 *
	 * @param busType the bus type of this bus
	 */
	public void setBusType(int busType);

	/**
	 * Returns the capacity of this bus.
	 *
	 * @return the capacity of this bus
	 */
	public int getCapacity();

	/**
	 * Sets the capacity of this bus.
	 *
	 * @param capacity the capacity of this bus
	 */
	public void setCapacity(int capacity);

	/**
	 * Returns the user ID of this bus.
	 *
	 * @return the user ID of this bus
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this bus.
	 *
	 * @param userId the user ID of this bus
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this bus.
	 *
	 * @return the user uuid of this bus
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this bus.
	 *
	 * @param userUuid the user uuid of this bus
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the image1 of this bus.
	 *
	 * @return the image1 of this bus
	 */
	@AutoEscape
	public String getImage1();

	/**
	 * Sets the image1 of this bus.
	 *
	 * @param image1 the image1 of this bus
	 */
	public void setImage1(String image1);

	/**
	 * Returns the image2 of this bus.
	 *
	 * @return the image2 of this bus
	 */
	@AutoEscape
	public String getImage2();

	/**
	 * Sets the image2 of this bus.
	 *
	 * @param image2 the image2 of this bus
	 */
	public void setImage2(String image2);

	/**
	 * Returns the image3 of this bus.
	 *
	 * @return the image3 of this bus
	 */
	@AutoEscape
	public String getImage3();

	/**
	 * Sets the image3 of this bus.
	 *
	 * @param image3 the image3 of this bus
	 */
	public void setImage3(String image3);

	/**
	 * Returns the image4 of this bus.
	 *
	 * @return the image4 of this bus
	 */
	@AutoEscape
	public String getImage4();

	/**
	 * Sets the image4 of this bus.
	 *
	 * @param image4 the image4 of this bus
	 */
	public void setImage4(String image4);

	/**
	 * Returns the image5 of this bus.
	 *
	 * @return the image5 of this bus
	 */
	@AutoEscape
	public String getImage5();

	/**
	 * Sets the image5 of this bus.
	 *
	 * @param image5 the image5 of this bus
	 */
	public void setImage5(String image5);

	@Override
	public Bus cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}