/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.esq.bus.reservation.slayers.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Discount service. Represents a row in the &quot;BOOKRESERVATION_Discount&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.esq.bus.reservation.slayers.model.impl.DiscountModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.esq.bus.reservation.slayers.model.impl.DiscountImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Discount
 * @generated
 */
@ProviderType
public interface DiscountModel extends BaseModel<Discount> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a discount model instance should use the {@link Discount} interface instead.
	 */

	/**
	 * Returns the primary key of this discount.
	 *
	 * @return the primary key of this discount
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this discount.
	 *
	 * @param primaryKey the primary key of this discount
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the discount ID of this discount.
	 *
	 * @return the discount ID of this discount
	 */
	public long getDiscountId();

	/**
	 * Sets the discount ID of this discount.
	 *
	 * @param discountId the discount ID of this discount
	 */
	public void setDiscountId(long discountId);

	/**
	 * Returns the code of this discount.
	 *
	 * @return the code of this discount
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this discount.
	 *
	 * @param code the code of this discount
	 */
	public void setCode(String code);

	/**
	 * Returns the percentage of this discount.
	 *
	 * @return the percentage of this discount
	 */
	public double getPercentage();

	/**
	 * Sets the percentage of this discount.
	 *
	 * @param percentage the percentage of this discount
	 */
	public void setPercentage(double percentage);

	/**
	 * Returns the valid from of this discount.
	 *
	 * @return the valid from of this discount
	 */
	public Date getValidFrom();

	/**
	 * Sets the valid from of this discount.
	 *
	 * @param validFrom the valid from of this discount
	 */
	public void setValidFrom(Date validFrom);

	/**
	 * Returns the valid to of this discount.
	 *
	 * @return the valid to of this discount
	 */
	public Date getValidTo();

	/**
	 * Sets the valid to of this discount.
	 *
	 * @param validTo the valid to of this discount
	 */
	public void setValidTo(Date validTo);

	@Override
	public Discount cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}