/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.esq.bus.reservation.slayers.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Feedback service. Represents a row in the &quot;BOOKRESERVATION_Feedback&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.esq.bus.reservation.slayers.model.impl.FeedbackModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.esq.bus.reservation.slayers.model.impl.FeedbackImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Feedback
 * @generated
 */
@ProviderType
public interface FeedbackModel extends BaseModel<Feedback> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a feedback model instance should use the {@link Feedback} interface instead.
	 */

	/**
	 * Returns the primary key of this feedback.
	 *
	 * @return the primary key of this feedback
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this feedback.
	 *
	 * @param primaryKey the primary key of this feedback
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the feedback ID of this feedback.
	 *
	 * @return the feedback ID of this feedback
	 */
	public long getFeedbackId();

	/**
	 * Sets the feedback ID of this feedback.
	 *
	 * @param feedbackId the feedback ID of this feedback
	 */
	public void setFeedbackId(long feedbackId);

	/**
	 * Returns the passenger ID of this feedback.
	 *
	 * @return the passenger ID of this feedback
	 */
	public long getPassengerId();

	/**
	 * Sets the passenger ID of this feedback.
	 *
	 * @param passengerId the passenger ID of this feedback
	 */
	public void setPassengerId(long passengerId);

	/**
	 * Returns the booking ID of this feedback.
	 *
	 * @return the booking ID of this feedback
	 */
	public long getBookingId();

	/**
	 * Sets the booking ID of this feedback.
	 *
	 * @param bookingId the booking ID of this feedback
	 */
	public void setBookingId(long bookingId);

	/**
	 * Returns the rating of this feedback.
	 *
	 * @return the rating of this feedback
	 */
	public int getRating();

	/**
	 * Sets the rating of this feedback.
	 *
	 * @param rating the rating of this feedback
	 */
	public void setRating(int rating);

	/**
	 * Returns the comment of this feedback.
	 *
	 * @return the comment of this feedback
	 */
	@AutoEscape
	public String getComment();

	/**
	 * Sets the comment of this feedback.
	 *
	 * @param comment the comment of this feedback
	 */
	public void setComment(String comment);

	@Override
	public Feedback cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}