/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.esq.bus.reservation.slayers.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Notification service. Represents a row in the &quot;BOOKRESERVATION_Notification&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.esq.bus.reservation.slayers.model.impl.NotificationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.esq.bus.reservation.slayers.model.impl.NotificationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Notification
 * @generated
 */
@ProviderType
public interface NotificationModel extends BaseModel<Notification> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a notification model instance should use the {@link Notification} interface instead.
	 */

	/**
	 * Returns the primary key of this notification.
	 *
	 * @return the primary key of this notification
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this notification.
	 *
	 * @param primaryKey the primary key of this notification
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the notification ID of this notification.
	 *
	 * @return the notification ID of this notification
	 */
	public long getNotificationId();

	/**
	 * Sets the notification ID of this notification.
	 *
	 * @param notificationId the notification ID of this notification
	 */
	public void setNotificationId(long notificationId);

	/**
	 * Returns the user ID of this notification.
	 *
	 * @return the user ID of this notification
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this notification.
	 *
	 * @param userId the user ID of this notification
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this notification.
	 *
	 * @return the user uuid of this notification
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this notification.
	 *
	 * @param userUuid the user uuid of this notification
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the message of this notification.
	 *
	 * @return the message of this notification
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this notification.
	 *
	 * @param message the message of this notification
	 */
	public void setMessage(String message);

	/**
	 * Returns the type of this notification.
	 *
	 * @return the type of this notification
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this notification.
	 *
	 * @param type the type of this notification
	 */
	public void setType(String type);

	/**
	 * Returns the sent date of this notification.
	 *
	 * @return the sent date of this notification
	 */
	public Date getSentDate();

	/**
	 * Sets the sent date of this notification.
	 *
	 * @param sentDate the sent date of this notification
	 */
	public void setSentDate(Date sentDate);

	@Override
	public Notification cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}