/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.esq.bus.reservation.slayers.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Passenger service. Represents a row in the &quot;BOOKRESERVATION_Passenger&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.esq.bus.reservation.slayers.model.impl.PassengerModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.esq.bus.reservation.slayers.model.impl.PassengerImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Passenger
 * @generated
 */
@ProviderType
public interface PassengerModel extends BaseModel<Passenger> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a passenger model instance should use the {@link Passenger} interface instead.
	 */

	/**
	 * Returns the primary key of this passenger.
	 *
	 * @return the primary key of this passenger
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this passenger.
	 *
	 * @param primaryKey the primary key of this passenger
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the passenger ID of this passenger.
	 *
	 * @return the passenger ID of this passenger
	 */
	public long getPassengerId();

	/**
	 * Sets the passenger ID of this passenger.
	 *
	 * @param passengerId the passenger ID of this passenger
	 */
	public void setPassengerId(long passengerId);

	/**
	 * Returns the passenger name of this passenger.
	 *
	 * @return the passenger name of this passenger
	 */
	@AutoEscape
	public String getPassengerName();

	/**
	 * Sets the passenger name of this passenger.
	 *
	 * @param passengerName the passenger name of this passenger
	 */
	public void setPassengerName(String passengerName);

	/**
	 * Returns the passenger contact of this passenger.
	 *
	 * @return the passenger contact of this passenger
	 */
	@AutoEscape
	public String getPassengerContact();

	/**
	 * Sets the passenger contact of this passenger.
	 *
	 * @param passengerContact the passenger contact of this passenger
	 */
	public void setPassengerContact(String passengerContact);

	/**
	 * Returns the passenger email of this passenger.
	 *
	 * @return the passenger email of this passenger
	 */
	@AutoEscape
	public String getPassengerEmail();

	/**
	 * Sets the passenger email of this passenger.
	 *
	 * @param passengerEmail the passenger email of this passenger
	 */
	public void setPassengerEmail(String passengerEmail);

	/**
	 * Returns the username of this passenger.
	 *
	 * @return the username of this passenger
	 */
	@AutoEscape
	public String getUsername();

	/**
	 * Sets the username of this passenger.
	 *
	 * @param username the username of this passenger
	 */
	public void setUsername(String username);

	/**
	 * Returns the password of this passenger.
	 *
	 * @return the password of this passenger
	 */
	@AutoEscape
	public String getPassword();

	/**
	 * Sets the password of this passenger.
	 *
	 * @param password the password of this passenger
	 */
	public void setPassword(String password);

	/**
	 * Returns the account status of this passenger.
	 *
	 * @return the account status of this passenger
	 */
	public int getAccountStatus();

	/**
	 * Sets the account status of this passenger.
	 *
	 * @param accountStatus the account status of this passenger
	 */
	public void setAccountStatus(int accountStatus);

	/**
	 * Returns the user ID of this passenger.
	 *
	 * @return the user ID of this passenger
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this passenger.
	 *
	 * @param userId the user ID of this passenger
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this passenger.
	 *
	 * @return the user uuid of this passenger
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this passenger.
	 *
	 * @param userUuid the user uuid of this passenger
	 */
	public void setUserUuid(String userUuid);

	@Override
	public Passenger cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}