/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.esq.bus.reservation.slayers.model;

import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Payment service. Represents a row in the &quot;BOOKRESERVATION_Payment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.esq.bus.reservation.slayers.model.impl.PaymentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.esq.bus.reservation.slayers.model.impl.PaymentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Payment
 * @generated
 */
@ProviderType
public interface PaymentModel extends BaseModel<Payment> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a payment model instance should use the {@link Payment} interface instead.
	 */

	/**
	 * Returns the primary key of this payment.
	 *
	 * @return the primary key of this payment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this payment.
	 *
	 * @param primaryKey the primary key of this payment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the payment ID of this payment.
	 *
	 * @return the payment ID of this payment
	 */
	public long getPaymentId();

	/**
	 * Sets the payment ID of this payment.
	 *
	 * @param paymentId the payment ID of this payment
	 */
	public void setPaymentId(long paymentId);

	/**
	 * Returns the booking ID of this payment.
	 *
	 * @return the booking ID of this payment
	 */
	public long getBookingId();

	/**
	 * Sets the booking ID of this payment.
	 *
	 * @param bookingId the booking ID of this payment
	 */
	public void setBookingId(long bookingId);

	/**
	 * Returns the amount paid of this payment.
	 *
	 * @return the amount paid of this payment
	 */
	public double getAmountPaid();

	/**
	 * Sets the amount paid of this payment.
	 *
	 * @param amountPaid the amount paid of this payment
	 */
	public void setAmountPaid(double amountPaid);

	/**
	 * Returns the payment date of this payment.
	 *
	 * @return the payment date of this payment
	 */
	public Date getPaymentDate();

	/**
	 * Sets the payment date of this payment.
	 *
	 * @param paymentDate the payment date of this payment
	 */
	public void setPaymentDate(Date paymentDate);

	/**
	 * Returns the user ID of this payment.
	 *
	 * @return the user ID of this payment
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this payment.
	 *
	 * @param userId the user ID of this payment
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this payment.
	 *
	 * @return the user uuid of this payment
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this payment.
	 *
	 * @param userUuid the user uuid of this payment
	 */
	public void setUserUuid(String userUuid);

	@Override
	public Payment cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}