/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.esq.bus.reservation.slayers.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the RefundRequest service. Represents a row in the &quot;BOOKRESERVATION_RefundRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.esq.bus.reservation.slayers.model.impl.RefundRequestModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.esq.bus.reservation.slayers.model.impl.RefundRequestImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RefundRequest
 * @generated
 */
@ProviderType
public interface RefundRequestModel extends BaseModel<RefundRequest> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a refund request model instance should use the {@link RefundRequest} interface instead.
	 */

	/**
	 * Returns the primary key of this refund request.
	 *
	 * @return the primary key of this refund request
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this refund request.
	 *
	 * @param primaryKey the primary key of this refund request
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the request ID of this refund request.
	 *
	 * @return the request ID of this refund request
	 */
	public long getRequestId();

	/**
	 * Sets the request ID of this refund request.
	 *
	 * @param requestId the request ID of this refund request
	 */
	public void setRequestId(long requestId);

	/**
	 * Returns the booking ID of this refund request.
	 *
	 * @return the booking ID of this refund request
	 */
	public long getBookingId();

	/**
	 * Sets the booking ID of this refund request.
	 *
	 * @param bookingId the booking ID of this refund request
	 */
	public void setBookingId(long bookingId);

	/**
	 * Returns the reason of this refund request.
	 *
	 * @return the reason of this refund request
	 */
	@AutoEscape
	public String getReason();

	/**
	 * Sets the reason of this refund request.
	 *
	 * @param reason the reason of this refund request
	 */
	public void setReason(String reason);

	/**
	 * Returns the status of this refund request.
	 *
	 * @return the status of this refund request
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this refund request.
	 *
	 * @param status the status of this refund request
	 */
	public void setStatus(String status);

	/**
	 * Returns the request date of this refund request.
	 *
	 * @return the request date of this refund request
	 */
	public Date getRequestDate();

	/**
	 * Sets the request date of this refund request.
	 *
	 * @param requestDate the request date of this refund request
	 */
	public void setRequestDate(Date requestDate);

	@Override
	public RefundRequest cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}