/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.esq.bus.reservation.slayers.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Seat service. Represents a row in the &quot;BOOKRESERVATION_Seat&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.esq.bus.reservation.slayers.model.impl.SeatModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.esq.bus.reservation.slayers.model.impl.SeatImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Seat
 * @generated
 */
@ProviderType
public interface SeatModel extends BaseModel<Seat> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a seat model instance should use the {@link Seat} interface instead.
	 */

	/**
	 * Returns the primary key of this seat.
	 *
	 * @return the primary key of this seat
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this seat.
	 *
	 * @param primaryKey the primary key of this seat
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the seat ID of this seat.
	 *
	 * @return the seat ID of this seat
	 */
	public long getSeatId();

	/**
	 * Sets the seat ID of this seat.
	 *
	 * @param seatId the seat ID of this seat
	 */
	public void setSeatId(long seatId);

	/**
	 * Returns the schedule ID of this seat.
	 *
	 * @return the schedule ID of this seat
	 */
	public long getScheduleId();

	/**
	 * Sets the schedule ID of this seat.
	 *
	 * @param scheduleId the schedule ID of this seat
	 */
	public void setScheduleId(long scheduleId);

	/**
	 * Returns the seat number of this seat.
	 *
	 * @return the seat number of this seat
	 */
	@AutoEscape
	public String getSeatNumber();

	/**
	 * Sets the seat number of this seat.
	 *
	 * @param seatNumber the seat number of this seat
	 */
	public void setSeatNumber(String seatNumber);

	/**
	 * Returns the is booked of this seat.
	 *
	 * @return the is booked of this seat
	 */
	public boolean getIsBooked();

	/**
	 * Returns <code>true</code> if this seat is is booked.
	 *
	 * @return <code>true</code> if this seat is is booked; <code>false</code> otherwise
	 */
	public boolean isIsBooked();

	/**
	 * Sets whether this seat is is booked.
	 *
	 * @param isBooked the is booked of this seat
	 */
	public void setIsBooked(boolean isBooked);

	@Override
	public Seat cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}