/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.esq.bus.reservation.slayers.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SupportTicket service. Represents a row in the &quot;BOOKRESERVATION_SupportTicket&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.esq.bus.reservation.slayers.model.impl.SupportTicketModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.esq.bus.reservation.slayers.model.impl.SupportTicketImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SupportTicket
 * @generated
 */
@ProviderType
public interface SupportTicketModel extends BaseModel<SupportTicket> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a support ticket model instance should use the {@link SupportTicket} interface instead.
	 */

	/**
	 * Returns the primary key of this support ticket.
	 *
	 * @return the primary key of this support ticket
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this support ticket.
	 *
	 * @param primaryKey the primary key of this support ticket
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the support ticket ID of this support ticket.
	 *
	 * @return the support ticket ID of this support ticket
	 */
	public long getSupportTicketId();

	/**
	 * Sets the support ticket ID of this support ticket.
	 *
	 * @param supportTicketId the support ticket ID of this support ticket
	 */
	public void setSupportTicketId(long supportTicketId);

	/**
	 * Returns the user ID of this support ticket.
	 *
	 * @return the user ID of this support ticket
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this support ticket.
	 *
	 * @param userId the user ID of this support ticket
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this support ticket.
	 *
	 * @return the user uuid of this support ticket
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this support ticket.
	 *
	 * @param userUuid the user uuid of this support ticket
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the subject of this support ticket.
	 *
	 * @return the subject of this support ticket
	 */
	@AutoEscape
	public String getSubject();

	/**
	 * Sets the subject of this support ticket.
	 *
	 * @param subject the subject of this support ticket
	 */
	public void setSubject(String subject);

	/**
	 * Returns the message of this support ticket.
	 *
	 * @return the message of this support ticket
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this support ticket.
	 *
	 * @param message the message of this support ticket
	 */
	public void setMessage(String message);

	/**
	 * Returns the status of this support ticket.
	 *
	 * @return the status of this support ticket
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this support ticket.
	 *
	 * @param status the status of this support ticket
	 */
	public void setStatus(String status);

	/**
	 * Returns the created date of this support ticket.
	 *
	 * @return the created date of this support ticket
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this support ticket.
	 *
	 * @param createdDate the created date of this support ticket
	 */
	public void setCreatedDate(Date createdDate);

	@Override
	public SupportTicket cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}