/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.esq.bus.reservation.slayers.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Ticket service. Represents a row in the &quot;BOOKRESERVATION_Ticket&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.esq.bus.reservation.slayers.model.impl.TicketModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.esq.bus.reservation.slayers.model.impl.TicketImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Ticket
 * @generated
 */
@ProviderType
public interface TicketModel extends BaseModel<Ticket> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ticket model instance should use the {@link Ticket} interface instead.
	 */

	/**
	 * Returns the primary key of this ticket.
	 *
	 * @return the primary key of this ticket
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ticket.
	 *
	 * @param primaryKey the primary key of this ticket
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ticket ID of this ticket.
	 *
	 * @return the ticket ID of this ticket
	 */
	public long getTicketId();

	/**
	 * Sets the ticket ID of this ticket.
	 *
	 * @param ticketId the ticket ID of this ticket
	 */
	public void setTicketId(long ticketId);

	/**
	 * Returns the booking ID of this ticket.
	 *
	 * @return the booking ID of this ticket
	 */
	public long getBookingId();

	/**
	 * Sets the booking ID of this ticket.
	 *
	 * @param bookingId the booking ID of this ticket
	 */
	public void setBookingId(long bookingId);

	/**
	 * Returns the qr code of this ticket.
	 *
	 * @return the qr code of this ticket
	 */
	@AutoEscape
	public String getQrCode();

	/**
	 * Sets the qr code of this ticket.
	 *
	 * @param qrCode the qr code of this ticket
	 */
	public void setQrCode(String qrCode);

	/**
	 * Returns the issued date of this ticket.
	 *
	 * @return the issued date of this ticket
	 */
	public Date getIssuedDate();

	/**
	 * Sets the issued date of this ticket.
	 *
	 * @param issuedDate the issued date of this ticket
	 */
	public void setIssuedDate(Date issuedDate);

	@Override
	public Ticket cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}