/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.esq.bus.reservation.slayers.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TransactionLog service. Represents a row in the &quot;BOOKRESERVATION_TransactionLog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.esq.bus.reservation.slayers.model.impl.TransactionLogModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.esq.bus.reservation.slayers.model.impl.TransactionLogImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TransactionLog
 * @generated
 */
@ProviderType
public interface TransactionLogModel extends BaseModel<TransactionLog> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a transaction log model instance should use the {@link TransactionLog} interface instead.
	 */

	/**
	 * Returns the primary key of this transaction log.
	 *
	 * @return the primary key of this transaction log
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this transaction log.
	 *
	 * @param primaryKey the primary key of this transaction log
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the log ID of this transaction log.
	 *
	 * @return the log ID of this transaction log
	 */
	public long getLogId();

	/**
	 * Sets the log ID of this transaction log.
	 *
	 * @param logId the log ID of this transaction log
	 */
	public void setLogId(long logId);

	/**
	 * Returns the action of this transaction log.
	 *
	 * @return the action of this transaction log
	 */
	@AutoEscape
	public String getAction();

	/**
	 * Sets the action of this transaction log.
	 *
	 * @param action the action of this transaction log
	 */
	public void setAction(String action);

	/**
	 * Returns the timestamp of this transaction log.
	 *
	 * @return the timestamp of this transaction log
	 */
	public Date getTimestamp();

	/**
	 * Sets the timestamp of this transaction log.
	 *
	 * @param timestamp the timestamp of this transaction log
	 */
	public void setTimestamp(Date timestamp);

	/**
	 * Returns the user ID of this transaction log.
	 *
	 * @return the user ID of this transaction log
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this transaction log.
	 *
	 * @param userId the user ID of this transaction log
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this transaction log.
	 *
	 * @return the user uuid of this transaction log
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this transaction log.
	 *
	 * @param userUuid the user uuid of this transaction log
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the booking ID of this transaction log.
	 *
	 * @return the booking ID of this transaction log
	 */
	public long getBookingId();

	/**
	 * Sets the booking ID of this transaction log.
	 *
	 * @param bookingId the booking ID of this transaction log
	 */
	public void setBookingId(long bookingId);

	@Override
	public TransactionLog cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}