/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.esq.bus.reservation.slayers.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TravelSchedule service. Represents a row in the &quot;BOOKRESERVATION_TravelSchedule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.esq.bus.reservation.slayers.model.impl.TravelScheduleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.esq.bus.reservation.slayers.model.impl.TravelScheduleImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TravelSchedule
 * @generated
 */
@ProviderType
public interface TravelScheduleModel extends BaseModel<TravelSchedule> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a travel schedule model instance should use the {@link TravelSchedule} interface instead.
	 */

	/**
	 * Returns the primary key of this travel schedule.
	 *
	 * @return the primary key of this travel schedule
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this travel schedule.
	 *
	 * @param primaryKey the primary key of this travel schedule
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the schedule ID of this travel schedule.
	 *
	 * @return the schedule ID of this travel schedule
	 */
	public long getScheduleId();

	/**
	 * Sets the schedule ID of this travel schedule.
	 *
	 * @param scheduleId the schedule ID of this travel schedule
	 */
	public void setScheduleId(long scheduleId);

	/**
	 * Returns the bus ID of this travel schedule.
	 *
	 * @return the bus ID of this travel schedule
	 */
	public long getBusId();

	/**
	 * Sets the bus ID of this travel schedule.
	 *
	 * @param busId the bus ID of this travel schedule
	 */
	public void setBusId(long busId);

	/**
	 * Returns the driver ID of this travel schedule.
	 *
	 * @return the driver ID of this travel schedule
	 */
	public long getDriverId();

	/**
	 * Sets the driver ID of this travel schedule.
	 *
	 * @param driverId the driver ID of this travel schedule
	 */
	public void setDriverId(long driverId);

	/**
	 * Returns the starting point of this travel schedule.
	 *
	 * @return the starting point of this travel schedule
	 */
	@AutoEscape
	public String getStartingPoint();

	/**
	 * Sets the starting point of this travel schedule.
	 *
	 * @param startingPoint the starting point of this travel schedule
	 */
	public void setStartingPoint(String startingPoint);

	/**
	 * Returns the destination of this travel schedule.
	 *
	 * @return the destination of this travel schedule
	 */
	@AutoEscape
	public String getDestination();

	/**
	 * Sets the destination of this travel schedule.
	 *
	 * @param destination the destination of this travel schedule
	 */
	public void setDestination(String destination);

	/**
	 * Returns the schedule date of this travel schedule.
	 *
	 * @return the schedule date of this travel schedule
	 */
	public Date getScheduleDate();

	/**
	 * Sets the schedule date of this travel schedule.
	 *
	 * @param scheduleDate the schedule date of this travel schedule
	 */
	public void setScheduleDate(Date scheduleDate);

	/**
	 * Returns the departure time of this travel schedule.
	 *
	 * @return the departure time of this travel schedule
	 */
	public Date getDepartureTime();

	/**
	 * Sets the departure time of this travel schedule.
	 *
	 * @param departureTime the departure time of this travel schedule
	 */
	public void setDepartureTime(Date departureTime);

	/**
	 * Returns the estimated arrival time of this travel schedule.
	 *
	 * @return the estimated arrival time of this travel schedule
	 */
	public Date getEstimatedArrivalTime();

	/**
	 * Sets the estimated arrival time of this travel schedule.
	 *
	 * @param estimatedArrivalTime the estimated arrival time of this travel schedule
	 */
	public void setEstimatedArrivalTime(Date estimatedArrivalTime);

	/**
	 * Returns the fare amount of this travel schedule.
	 *
	 * @return the fare amount of this travel schedule
	 */
	public double getFareAmount();

	/**
	 * Sets the fare amount of this travel schedule.
	 *
	 * @param fareAmount the fare amount of this travel schedule
	 */
	public void setFareAmount(double fareAmount);

	/**
	 * Returns the remarks of this travel schedule.
	 *
	 * @return the remarks of this travel schedule
	 */
	@AutoEscape
	public String getRemarks();

	/**
	 * Sets the remarks of this travel schedule.
	 *
	 * @param remarks the remarks of this travel schedule
	 */
	public void setRemarks(String remarks);

	/**
	 * Returns the user ID of this travel schedule.
	 *
	 * @return the user ID of this travel schedule
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this travel schedule.
	 *
	 * @param userId the user ID of this travel schedule
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this travel schedule.
	 *
	 * @return the user uuid of this travel schedule
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this travel schedule.
	 *
	 * @param userUuid the user uuid of this travel schedule
	 */
	public void setUserUuid(String userUuid);

	@Override
	public TravelSchedule cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}