/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.esq.bus.reservation.slayers.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the User service. Represents a row in the &quot;BOOKRESERVATION_User&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.esq.bus.reservation.slayers.model.impl.UserModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.esq.bus.reservation.slayers.model.impl.UserImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see User
 * @generated
 */
@ProviderType
public interface UserModel extends BaseModel<User> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user model instance should use the {@link User} interface instead.
	 */

	/**
	 * Returns the primary key of this user.
	 *
	 * @return the primary key of this user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user.
	 *
	 * @param primaryKey the primary key of this user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user ID of this user.
	 *
	 * @return the user ID of this user
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user.
	 *
	 * @param userId the user ID of this user
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user.
	 *
	 * @return the user uuid of this user
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user.
	 *
	 * @param userUuid the user uuid of this user
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the full name of this user.
	 *
	 * @return the full name of this user
	 */
	@AutoEscape
	public String getFullName();

	/**
	 * Sets the full name of this user.
	 *
	 * @param fullName the full name of this user
	 */
	public void setFullName(String fullName);

	/**
	 * Returns the contact no of this user.
	 *
	 * @return the contact no of this user
	 */
	@AutoEscape
	public String getContactNo();

	/**
	 * Sets the contact no of this user.
	 *
	 * @param contactNo the contact no of this user
	 */
	public void setContactNo(String contactNo);

	/**
	 * Returns the email address of this user.
	 *
	 * @return the email address of this user
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this user.
	 *
	 * @param emailAddress the email address of this user
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the username of this user.
	 *
	 * @return the username of this user
	 */
	@AutoEscape
	public String getUsername();

	/**
	 * Sets the username of this user.
	 *
	 * @param username the username of this user
	 */
	public void setUsername(String username);

	/**
	 * Returns the userpassword of this user.
	 *
	 * @return the userpassword of this user
	 */
	@AutoEscape
	public String getUserpassword();

	/**
	 * Sets the userpassword of this user.
	 *
	 * @param userpassword the userpassword of this user
	 */
	public void setUserpassword(String userpassword);

	/**
	 * Returns the account category of this user.
	 *
	 * @return the account category of this user
	 */
	public int getAccountCategory();

	/**
	 * Sets the account category of this user.
	 *
	 * @param accountCategory the account category of this user
	 */
	public void setAccountCategory(int accountCategory);

	/**
	 * Returns the account status of this user.
	 *
	 * @return the account status of this user
	 */
	public int getAccountStatus();

	/**
	 * Sets the account status of this user.
	 *
	 * @param accountStatus the account status of this user
	 */
	public void setAccountStatus(int accountStatus);

	@Override
	public User cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}