/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.esq.bus.reservation.slayers.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserRole service. Represents a row in the &quot;BOOKRESERVATION_UserRole&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.esq.bus.reservation.slayers.model.impl.UserRoleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.esq.bus.reservation.slayers.model.impl.UserRoleImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserRole
 * @generated
 */
@ProviderType
public interface UserRoleModel extends BaseModel<UserRole> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user role model instance should use the {@link UserRole} interface instead.
	 */

	/**
	 * Returns the primary key of this user role.
	 *
	 * @return the primary key of this user role
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user role.
	 *
	 * @param primaryKey the primary key of this user role
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user role ID of this user role.
	 *
	 * @return the user role ID of this user role
	 */
	public long getUserRoleId();

	/**
	 * Sets the user role ID of this user role.
	 *
	 * @param userRoleId the user role ID of this user role
	 */
	public void setUserRoleId(long userRoleId);

	/**
	 * Returns the user ID of this user role.
	 *
	 * @return the user ID of this user role
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user role.
	 *
	 * @param userId the user ID of this user role
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user role.
	 *
	 * @return the user uuid of this user role
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user role.
	 *
	 * @param userUuid the user uuid of this user role
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the role name of this user role.
	 *
	 * @return the role name of this user role
	 */
	@AutoEscape
	public String getRoleName();

	/**
	 * Sets the role name of this user role.
	 *
	 * @param roleName the role name of this user role
	 */
	public void setRoleName(String roleName);

	@Override
	public UserRole cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}