/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.esq.bus.reservation.slayers.model.impl;

import com.esq.bus.reservation.slayers.model.AuditLog;
import com.esq.bus.reservation.slayers.model.AuditLogModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AuditLog service. Represents a row in the &quot;BOOKRESERVATION_AuditLog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AuditLogModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AuditLogImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AuditLogImpl
 * @generated
 */
public class AuditLogModelImpl
	extends BaseModelImpl<AuditLog> implements AuditLogModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a audit log model instance should use the <code>AuditLog</code> interface instead.
	 */
	public static final String TABLE_NAME = "BOOKRESERVATION_AuditLog";

	public static final Object[][] TABLE_COLUMNS = {
		{"auditId", Types.BIGINT}, {"entityName", Types.VARCHAR},
		{"entityId", Types.BIGINT}, {"action", Types.VARCHAR},
		{"userId", Types.BIGINT}, {"actionDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("auditId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("entityName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("entityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("action", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("actionDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table BOOKRESERVATION_AuditLog (auditId LONG not null primary key,entityName VARCHAR(75) null,entityId LONG,action VARCHAR(75) null,userId LONG,actionDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table BOOKRESERVATION_AuditLog";

	public static final String ORDER_BY_JPQL = " ORDER BY auditLog.auditId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY BOOKRESERVATION_AuditLog.auditId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ACTIONDATE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long AUDITID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AuditLogModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _auditId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAuditId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _auditId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AuditLog.class;
	}

	@Override
	public String getModelClassName() {
		return AuditLog.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AuditLog, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AuditLog, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AuditLog, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((AuditLog)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AuditLog, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AuditLog, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AuditLog)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AuditLog, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AuditLog, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<AuditLog, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<AuditLog, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<AuditLog, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<AuditLog, Object>>();
		Map<String, BiConsumer<AuditLog, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<AuditLog, ?>>();

		attributeGetterFunctions.put("auditId", AuditLog::getAuditId);
		attributeSetterBiConsumers.put(
			"auditId", (BiConsumer<AuditLog, Long>)AuditLog::setAuditId);
		attributeGetterFunctions.put("entityName", AuditLog::getEntityName);
		attributeSetterBiConsumers.put(
			"entityName",
			(BiConsumer<AuditLog, String>)AuditLog::setEntityName);
		attributeGetterFunctions.put("entityId", AuditLog::getEntityId);
		attributeSetterBiConsumers.put(
			"entityId", (BiConsumer<AuditLog, Long>)AuditLog::setEntityId);
		attributeGetterFunctions.put("action", AuditLog::getAction);
		attributeSetterBiConsumers.put(
			"action", (BiConsumer<AuditLog, String>)AuditLog::setAction);
		attributeGetterFunctions.put("userId", AuditLog::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<AuditLog, Long>)AuditLog::setUserId);
		attributeGetterFunctions.put("actionDate", AuditLog::getActionDate);
		attributeSetterBiConsumers.put(
			"actionDate", (BiConsumer<AuditLog, Date>)AuditLog::setActionDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getAuditId() {
		return _auditId;
	}

	@Override
	public void setAuditId(long auditId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_auditId = auditId;
	}

	@Override
	public String getEntityName() {
		if (_entityName == null) {
			return "";
		}
		else {
			return _entityName;
		}
	}

	@Override
	public void setEntityName(String entityName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entityName = entityName;
	}

	@Override
	public long getEntityId() {
		return _entityId;
	}

	@Override
	public void setEntityId(long entityId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entityId = entityId;
	}

	@Override
	public String getAction() {
		if (_action == null) {
			return "";
		}
		else {
			return _action;
		}
	}

	@Override
	public void setAction(String action) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_action = action;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public Date getActionDate() {
		return _actionDate;
	}

	@Override
	public void setActionDate(Date actionDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_actionDate = actionDate;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Date getOriginalActionDate() {
		return getColumnOriginalValue("actionDate");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, AuditLog.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AuditLog toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AuditLog>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AuditLogImpl auditLogImpl = new AuditLogImpl();

		auditLogImpl.setAuditId(getAuditId());
		auditLogImpl.setEntityName(getEntityName());
		auditLogImpl.setEntityId(getEntityId());
		auditLogImpl.setAction(getAction());
		auditLogImpl.setUserId(getUserId());
		auditLogImpl.setActionDate(getActionDate());

		auditLogImpl.resetOriginalValues();

		return auditLogImpl;
	}

	@Override
	public AuditLog cloneWithOriginalValues() {
		AuditLogImpl auditLogImpl = new AuditLogImpl();

		auditLogImpl.setAuditId(this.<Long>getColumnOriginalValue("auditId"));
		auditLogImpl.setEntityName(
			this.<String>getColumnOriginalValue("entityName"));
		auditLogImpl.setEntityId(this.<Long>getColumnOriginalValue("entityId"));
		auditLogImpl.setAction(this.<String>getColumnOriginalValue("action"));
		auditLogImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		auditLogImpl.setActionDate(
			this.<Date>getColumnOriginalValue("actionDate"));

		return auditLogImpl;
	}

	@Override
	public int compareTo(AuditLog auditLog) {
		long primaryKey = auditLog.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AuditLog)) {
			return false;
		}

		AuditLog auditLog = (AuditLog)object;

		long primaryKey = auditLog.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AuditLog> toCacheModel() {
		AuditLogCacheModel auditLogCacheModel = new AuditLogCacheModel();

		auditLogCacheModel.auditId = getAuditId();

		auditLogCacheModel.entityName = getEntityName();

		String entityName = auditLogCacheModel.entityName;

		if ((entityName != null) && (entityName.length() == 0)) {
			auditLogCacheModel.entityName = null;
		}

		auditLogCacheModel.entityId = getEntityId();

		auditLogCacheModel.action = getAction();

		String action = auditLogCacheModel.action;

		if ((action != null) && (action.length() == 0)) {
			auditLogCacheModel.action = null;
		}

		auditLogCacheModel.userId = getUserId();

		Date actionDate = getActionDate();

		if (actionDate != null) {
			auditLogCacheModel.actionDate = actionDate.getTime();
		}
		else {
			auditLogCacheModel.actionDate = Long.MIN_VALUE;
		}

		return auditLogCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AuditLog, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AuditLog, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AuditLog, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((AuditLog)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AuditLog>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AuditLog.class, ModelWrapper.class);

	}

	private long _auditId;
	private String _entityName;
	private long _entityId;
	private String _action;
	private long _userId;
	private Date _actionDate;

	public <T> T getColumnValue(String columnName) {
		Function<AuditLog, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AuditLog)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("auditId", _auditId);
		_columnOriginalValues.put("entityName", _entityName);
		_columnOriginalValues.put("entityId", _entityId);
		_columnOriginalValues.put("action", _action);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("actionDate", _actionDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("auditId", 1L);

		columnBitmasks.put("entityName", 2L);

		columnBitmasks.put("entityId", 4L);

		columnBitmasks.put("action", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("actionDate", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AuditLog _escapedModel;

}