/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.esq.bus.reservation.slayers.model.impl;

import com.esq.bus.reservation.slayers.model.Booking;
import com.esq.bus.reservation.slayers.model.BookingModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Booking service. Represents a row in the &quot;BOOKRESERVATION_Booking&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>BookingModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BookingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BookingImpl
 * @generated
 */
public class BookingModelImpl
	extends BaseModelImpl<Booking> implements BookingModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a booking model instance should use the <code>Booking</code> interface instead.
	 */
	public static final String TABLE_NAME = "BOOKRESERVATION_Booking";

	public static final Object[][] TABLE_COLUMNS = {
		{"bookingId", Types.BIGINT}, {"scheduleId", Types.BIGINT},
		{"passengerId", Types.BIGINT}, {"numberOfSeats", Types.INTEGER},
		{"fareAmount", Types.DOUBLE}, {"totalAmount", Types.DOUBLE},
		{"dateOfBooking", Types.TIMESTAMP}, {"bookingStatus", Types.INTEGER},
		{"userId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("bookingId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("scheduleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("passengerId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("numberOfSeats", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("fareAmount", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("totalAmount", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("dateOfBooking", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("bookingStatus", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table BOOKRESERVATION_Booking (bookingId LONG not null primary key,scheduleId LONG,passengerId LONG,numberOfSeats INTEGER,fareAmount DOUBLE,totalAmount DOUBLE,dateOfBooking DATE null,bookingStatus INTEGER,userId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table BOOKRESERVATION_Booking";

	public static final String ORDER_BY_JPQL =
		" ORDER BY booking.bookingId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY BOOKRESERVATION_Booking.bookingId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PASSENGERID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SCHEDULEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long BOOKINGID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public BookingModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _bookingId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBookingId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _bookingId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Booking.class;
	}

	@Override
	public String getModelClassName() {
		return Booking.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Booking, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Booking, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Booking, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Booking)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Booking, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Booking, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Booking)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Booking, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Booking, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Booking, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Booking, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Booking, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Booking, Object>>();
		Map<String, BiConsumer<Booking, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Booking, ?>>();

		attributeGetterFunctions.put("bookingId", Booking::getBookingId);
		attributeSetterBiConsumers.put(
			"bookingId", (BiConsumer<Booking, Long>)Booking::setBookingId);
		attributeGetterFunctions.put("scheduleId", Booking::getScheduleId);
		attributeSetterBiConsumers.put(
			"scheduleId", (BiConsumer<Booking, Long>)Booking::setScheduleId);
		attributeGetterFunctions.put("passengerId", Booking::getPassengerId);
		attributeSetterBiConsumers.put(
			"passengerId", (BiConsumer<Booking, Long>)Booking::setPassengerId);
		attributeGetterFunctions.put(
			"numberOfSeats", Booking::getNumberOfSeats);
		attributeSetterBiConsumers.put(
			"numberOfSeats",
			(BiConsumer<Booking, Integer>)Booking::setNumberOfSeats);
		attributeGetterFunctions.put("fareAmount", Booking::getFareAmount);
		attributeSetterBiConsumers.put(
			"fareAmount", (BiConsumer<Booking, Double>)Booking::setFareAmount);
		attributeGetterFunctions.put("totalAmount", Booking::getTotalAmount);
		attributeSetterBiConsumers.put(
			"totalAmount",
			(BiConsumer<Booking, Double>)Booking::setTotalAmount);
		attributeGetterFunctions.put(
			"dateOfBooking", Booking::getDateOfBooking);
		attributeSetterBiConsumers.put(
			"dateOfBooking",
			(BiConsumer<Booking, Date>)Booking::setDateOfBooking);
		attributeGetterFunctions.put(
			"bookingStatus", Booking::getBookingStatus);
		attributeSetterBiConsumers.put(
			"bookingStatus",
			(BiConsumer<Booking, Integer>)Booking::setBookingStatus);
		attributeGetterFunctions.put("userId", Booking::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Booking, Long>)Booking::setUserId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getBookingId() {
		return _bookingId;
	}

	@Override
	public void setBookingId(long bookingId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_bookingId = bookingId;
	}

	@Override
	public long getScheduleId() {
		return _scheduleId;
	}

	@Override
	public void setScheduleId(long scheduleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_scheduleId = scheduleId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalScheduleId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("scheduleId"));
	}

	@Override
	public long getPassengerId() {
		return _passengerId;
	}

	@Override
	public void setPassengerId(long passengerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_passengerId = passengerId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPassengerId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("passengerId"));
	}

	@Override
	public int getNumberOfSeats() {
		return _numberOfSeats;
	}

	@Override
	public void setNumberOfSeats(int numberOfSeats) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_numberOfSeats = numberOfSeats;
	}

	@Override
	public double getFareAmount() {
		return _fareAmount;
	}

	@Override
	public void setFareAmount(double fareAmount) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fareAmount = fareAmount;
	}

	@Override
	public double getTotalAmount() {
		return _totalAmount;
	}

	@Override
	public void setTotalAmount(double totalAmount) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_totalAmount = totalAmount;
	}

	@Override
	public Date getDateOfBooking() {
		return _dateOfBooking;
	}

	@Override
	public void setDateOfBooking(Date dateOfBooking) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dateOfBooking = dateOfBooking;
	}

	@Override
	public int getBookingStatus() {
		return _bookingStatus;
	}

	@Override
	public void setBookingStatus(int bookingStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_bookingStatus = bookingStatus;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Booking.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Booking toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Booking>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BookingImpl bookingImpl = new BookingImpl();

		bookingImpl.setBookingId(getBookingId());
		bookingImpl.setScheduleId(getScheduleId());
		bookingImpl.setPassengerId(getPassengerId());
		bookingImpl.setNumberOfSeats(getNumberOfSeats());
		bookingImpl.setFareAmount(getFareAmount());
		bookingImpl.setTotalAmount(getTotalAmount());
		bookingImpl.setDateOfBooking(getDateOfBooking());
		bookingImpl.setBookingStatus(getBookingStatus());
		bookingImpl.setUserId(getUserId());

		bookingImpl.resetOriginalValues();

		return bookingImpl;
	}

	@Override
	public Booking cloneWithOriginalValues() {
		BookingImpl bookingImpl = new BookingImpl();

		bookingImpl.setBookingId(
			this.<Long>getColumnOriginalValue("bookingId"));
		bookingImpl.setScheduleId(
			this.<Long>getColumnOriginalValue("scheduleId"));
		bookingImpl.setPassengerId(
			this.<Long>getColumnOriginalValue("passengerId"));
		bookingImpl.setNumberOfSeats(
			this.<Integer>getColumnOriginalValue("numberOfSeats"));
		bookingImpl.setFareAmount(
			this.<Double>getColumnOriginalValue("fareAmount"));
		bookingImpl.setTotalAmount(
			this.<Double>getColumnOriginalValue("totalAmount"));
		bookingImpl.setDateOfBooking(
			this.<Date>getColumnOriginalValue("dateOfBooking"));
		bookingImpl.setBookingStatus(
			this.<Integer>getColumnOriginalValue("bookingStatus"));
		bookingImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));

		return bookingImpl;
	}

	@Override
	public int compareTo(Booking booking) {
		long primaryKey = booking.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Booking)) {
			return false;
		}

		Booking booking = (Booking)object;

		long primaryKey = booking.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Booking> toCacheModel() {
		BookingCacheModel bookingCacheModel = new BookingCacheModel();

		bookingCacheModel.bookingId = getBookingId();

		bookingCacheModel.scheduleId = getScheduleId();

		bookingCacheModel.passengerId = getPassengerId();

		bookingCacheModel.numberOfSeats = getNumberOfSeats();

		bookingCacheModel.fareAmount = getFareAmount();

		bookingCacheModel.totalAmount = getTotalAmount();

		Date dateOfBooking = getDateOfBooking();

		if (dateOfBooking != null) {
			bookingCacheModel.dateOfBooking = dateOfBooking.getTime();
		}
		else {
			bookingCacheModel.dateOfBooking = Long.MIN_VALUE;
		}

		bookingCacheModel.bookingStatus = getBookingStatus();

		bookingCacheModel.userId = getUserId();

		return bookingCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Booking, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Booking, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Booking, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Booking)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Booking>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Booking.class, ModelWrapper.class);

	}

	private long _bookingId;
	private long _scheduleId;
	private long _passengerId;
	private int _numberOfSeats;
	private double _fareAmount;
	private double _totalAmount;
	private Date _dateOfBooking;
	private int _bookingStatus;
	private long _userId;

	public <T> T getColumnValue(String columnName) {
		Function<Booking, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Booking)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("bookingId", _bookingId);
		_columnOriginalValues.put("scheduleId", _scheduleId);
		_columnOriginalValues.put("passengerId", _passengerId);
		_columnOriginalValues.put("numberOfSeats", _numberOfSeats);
		_columnOriginalValues.put("fareAmount", _fareAmount);
		_columnOriginalValues.put("totalAmount", _totalAmount);
		_columnOriginalValues.put("dateOfBooking", _dateOfBooking);
		_columnOriginalValues.put("bookingStatus", _bookingStatus);
		_columnOriginalValues.put("userId", _userId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("bookingId", 1L);

		columnBitmasks.put("scheduleId", 2L);

		columnBitmasks.put("passengerId", 4L);

		columnBitmasks.put("numberOfSeats", 8L);

		columnBitmasks.put("fareAmount", 16L);

		columnBitmasks.put("totalAmount", 32L);

		columnBitmasks.put("dateOfBooking", 64L);

		columnBitmasks.put("bookingStatus", 128L);

		columnBitmasks.put("userId", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Booking _escapedModel;

}