/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.esq.bus.reservation.slayers.model.impl;

import com.esq.bus.reservation.slayers.model.Driver;
import com.esq.bus.reservation.slayers.model.DriverModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Driver service. Represents a row in the &quot;BOOKRESERVATION_Driver&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DriverModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DriverImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DriverImpl
 * @generated
 */
public class DriverModelImpl
	extends BaseModelImpl<Driver> implements DriverModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a driver model instance should use the <code>Driver</code> interface instead.
	 */
	public static final String TABLE_NAME = "BOOKRESERVATION_Driver";

	public static final Object[][] TABLE_COLUMNS = {
		{"driverId", Types.BIGINT}, {"driverName", Types.VARCHAR},
		{"driverContact", Types.VARCHAR}, {"userId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("driverId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("driverName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("driverContact", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table BOOKRESERVATION_Driver (driverId LONG not null primary key,driverName VARCHAR(75) null,driverContact VARCHAR(75) null,userId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table BOOKRESERVATION_Driver";

	public static final String ORDER_BY_JPQL = " ORDER BY driver.driverId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY BOOKRESERVATION_Driver.driverId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DRIVERID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public DriverModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _driverId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDriverId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _driverId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Driver.class;
	}

	@Override
	public String getModelClassName() {
		return Driver.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Driver, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Driver, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Driver, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Driver)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Driver, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Driver, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Driver)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Driver, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Driver, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Driver, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Driver, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Driver, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Driver, Object>>();
		Map<String, BiConsumer<Driver, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Driver, ?>>();

		attributeGetterFunctions.put("driverId", Driver::getDriverId);
		attributeSetterBiConsumers.put(
			"driverId", (BiConsumer<Driver, Long>)Driver::setDriverId);
		attributeGetterFunctions.put("driverName", Driver::getDriverName);
		attributeSetterBiConsumers.put(
			"driverName", (BiConsumer<Driver, String>)Driver::setDriverName);
		attributeGetterFunctions.put("driverContact", Driver::getDriverContact);
		attributeSetterBiConsumers.put(
			"driverContact",
			(BiConsumer<Driver, String>)Driver::setDriverContact);
		attributeGetterFunctions.put("userId", Driver::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Driver, Long>)Driver::setUserId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getDriverId() {
		return _driverId;
	}

	@Override
	public void setDriverId(long driverId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_driverId = driverId;
	}

	@Override
	public String getDriverName() {
		if (_driverName == null) {
			return "";
		}
		else {
			return _driverName;
		}
	}

	@Override
	public void setDriverName(String driverName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_driverName = driverName;
	}

	@Override
	public String getDriverContact() {
		if (_driverContact == null) {
			return "";
		}
		else {
			return _driverContact;
		}
	}

	@Override
	public void setDriverContact(String driverContact) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_driverContact = driverContact;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Driver.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Driver toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Driver>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DriverImpl driverImpl = new DriverImpl();

		driverImpl.setDriverId(getDriverId());
		driverImpl.setDriverName(getDriverName());
		driverImpl.setDriverContact(getDriverContact());
		driverImpl.setUserId(getUserId());

		driverImpl.resetOriginalValues();

		return driverImpl;
	}

	@Override
	public Driver cloneWithOriginalValues() {
		DriverImpl driverImpl = new DriverImpl();

		driverImpl.setDriverId(this.<Long>getColumnOriginalValue("driverId"));
		driverImpl.setDriverName(
			this.<String>getColumnOriginalValue("driverName"));
		driverImpl.setDriverContact(
			this.<String>getColumnOriginalValue("driverContact"));
		driverImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));

		return driverImpl;
	}

	@Override
	public int compareTo(Driver driver) {
		long primaryKey = driver.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Driver)) {
			return false;
		}

		Driver driver = (Driver)object;

		long primaryKey = driver.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Driver> toCacheModel() {
		DriverCacheModel driverCacheModel = new DriverCacheModel();

		driverCacheModel.driverId = getDriverId();

		driverCacheModel.driverName = getDriverName();

		String driverName = driverCacheModel.driverName;

		if ((driverName != null) && (driverName.length() == 0)) {
			driverCacheModel.driverName = null;
		}

		driverCacheModel.driverContact = getDriverContact();

		String driverContact = driverCacheModel.driverContact;

		if ((driverContact != null) && (driverContact.length() == 0)) {
			driverCacheModel.driverContact = null;
		}

		driverCacheModel.userId = getUserId();

		return driverCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Driver, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Driver, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Driver, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Driver)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Driver>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Driver.class, ModelWrapper.class);

	}

	private long _driverId;
	private String _driverName;
	private String _driverContact;
	private long _userId;

	public <T> T getColumnValue(String columnName) {
		Function<Driver, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Driver)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("driverId", _driverId);
		_columnOriginalValues.put("driverName", _driverName);
		_columnOriginalValues.put("driverContact", _driverContact);
		_columnOriginalValues.put("userId", _userId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("driverId", 1L);

		columnBitmasks.put("driverName", 2L);

		columnBitmasks.put("driverContact", 4L);

		columnBitmasks.put("userId", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Driver _escapedModel;

}