/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.esq.bus.reservation.slayers.model.impl;

import com.esq.bus.reservation.slayers.model.Payment;
import com.esq.bus.reservation.slayers.model.PaymentModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Payment service. Represents a row in the &quot;BOOKRESERVATION_Payment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PaymentModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PaymentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PaymentImpl
 * @generated
 */
public class PaymentModelImpl
	extends BaseModelImpl<Payment> implements PaymentModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a payment model instance should use the <code>Payment</code> interface instead.
	 */
	public static final String TABLE_NAME = "BOOKRESERVATION_Payment";

	public static final Object[][] TABLE_COLUMNS = {
		{"paymentId", Types.BIGINT}, {"bookingId", Types.BIGINT},
		{"amountPaid", Types.DOUBLE}, {"paymentDate", Types.TIMESTAMP},
		{"userId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("paymentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("bookingId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("amountPaid", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("paymentDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table BOOKRESERVATION_Payment (paymentId LONG not null primary key,bookingId LONG,amountPaid DOUBLE,paymentDate DATE null,userId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table BOOKRESERVATION_Payment";

	public static final String ORDER_BY_JPQL =
		" ORDER BY payment.paymentId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY BOOKRESERVATION_Payment.paymentId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long BOOKINGID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PAYMENTID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PaymentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _paymentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPaymentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _paymentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Payment.class;
	}

	@Override
	public String getModelClassName() {
		return Payment.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Payment, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Payment, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Payment, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Payment)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Payment, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Payment, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Payment)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Payment, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Payment, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Payment, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Payment, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Payment, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Payment, Object>>();
		Map<String, BiConsumer<Payment, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Payment, ?>>();

		attributeGetterFunctions.put("paymentId", Payment::getPaymentId);
		attributeSetterBiConsumers.put(
			"paymentId", (BiConsumer<Payment, Long>)Payment::setPaymentId);
		attributeGetterFunctions.put("bookingId", Payment::getBookingId);
		attributeSetterBiConsumers.put(
			"bookingId", (BiConsumer<Payment, Long>)Payment::setBookingId);
		attributeGetterFunctions.put("amountPaid", Payment::getAmountPaid);
		attributeSetterBiConsumers.put(
			"amountPaid", (BiConsumer<Payment, Double>)Payment::setAmountPaid);
		attributeGetterFunctions.put("paymentDate", Payment::getPaymentDate);
		attributeSetterBiConsumers.put(
			"paymentDate", (BiConsumer<Payment, Date>)Payment::setPaymentDate);
		attributeGetterFunctions.put("userId", Payment::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Payment, Long>)Payment::setUserId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getPaymentId() {
		return _paymentId;
	}

	@Override
	public void setPaymentId(long paymentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_paymentId = paymentId;
	}

	@Override
	public long getBookingId() {
		return _bookingId;
	}

	@Override
	public void setBookingId(long bookingId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_bookingId = bookingId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalBookingId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("bookingId"));
	}

	@Override
	public double getAmountPaid() {
		return _amountPaid;
	}

	@Override
	public void setAmountPaid(double amountPaid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_amountPaid = amountPaid;
	}

	@Override
	public Date getPaymentDate() {
		return _paymentDate;
	}

	@Override
	public void setPaymentDate(Date paymentDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_paymentDate = paymentDate;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Payment.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Payment toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Payment>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PaymentImpl paymentImpl = new PaymentImpl();

		paymentImpl.setPaymentId(getPaymentId());
		paymentImpl.setBookingId(getBookingId());
		paymentImpl.setAmountPaid(getAmountPaid());
		paymentImpl.setPaymentDate(getPaymentDate());
		paymentImpl.setUserId(getUserId());

		paymentImpl.resetOriginalValues();

		return paymentImpl;
	}

	@Override
	public Payment cloneWithOriginalValues() {
		PaymentImpl paymentImpl = new PaymentImpl();

		paymentImpl.setPaymentId(
			this.<Long>getColumnOriginalValue("paymentId"));
		paymentImpl.setBookingId(
			this.<Long>getColumnOriginalValue("bookingId"));
		paymentImpl.setAmountPaid(
			this.<Double>getColumnOriginalValue("amountPaid"));
		paymentImpl.setPaymentDate(
			this.<Date>getColumnOriginalValue("paymentDate"));
		paymentImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));

		return paymentImpl;
	}

	@Override
	public int compareTo(Payment payment) {
		long primaryKey = payment.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Payment)) {
			return false;
		}

		Payment payment = (Payment)object;

		long primaryKey = payment.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Payment> toCacheModel() {
		PaymentCacheModel paymentCacheModel = new PaymentCacheModel();

		paymentCacheModel.paymentId = getPaymentId();

		paymentCacheModel.bookingId = getBookingId();

		paymentCacheModel.amountPaid = getAmountPaid();

		Date paymentDate = getPaymentDate();

		if (paymentDate != null) {
			paymentCacheModel.paymentDate = paymentDate.getTime();
		}
		else {
			paymentCacheModel.paymentDate = Long.MIN_VALUE;
		}

		paymentCacheModel.userId = getUserId();

		return paymentCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Payment, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Payment, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Payment, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Payment)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Payment>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Payment.class, ModelWrapper.class);

	}

	private long _paymentId;
	private long _bookingId;
	private double _amountPaid;
	private Date _paymentDate;
	private long _userId;

	public <T> T getColumnValue(String columnName) {
		Function<Payment, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Payment)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("paymentId", _paymentId);
		_columnOriginalValues.put("bookingId", _bookingId);
		_columnOriginalValues.put("amountPaid", _amountPaid);
		_columnOriginalValues.put("paymentDate", _paymentDate);
		_columnOriginalValues.put("userId", _userId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("paymentId", 1L);

		columnBitmasks.put("bookingId", 2L);

		columnBitmasks.put("amountPaid", 4L);

		columnBitmasks.put("paymentDate", 8L);

		columnBitmasks.put("userId", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Payment _escapedModel;

}