/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.esq.bus.reservation.slayers.model.impl;

import com.esq.bus.reservation.slayers.model.RefundRequest;
import com.esq.bus.reservation.slayers.model.RefundRequestModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the RefundRequest service. Represents a row in the &quot;BOOKRESERVATION_RefundRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>RefundRequestModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RefundRequestImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RefundRequestImpl
 * @generated
 */
public class RefundRequestModelImpl
	extends BaseModelImpl<RefundRequest> implements RefundRequestModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a refund request model instance should use the <code>RefundRequest</code> interface instead.
	 */
	public static final String TABLE_NAME = "BOOKRESERVATION_RefundRequest";

	public static final Object[][] TABLE_COLUMNS = {
		{"requestId", Types.BIGINT}, {"bookingId", Types.BIGINT},
		{"reason", Types.VARCHAR}, {"status", Types.VARCHAR},
		{"requestDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("requestId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("bookingId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("reason", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("requestDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table BOOKRESERVATION_RefundRequest (requestId LONG not null primary key,bookingId LONG,reason VARCHAR(75) null,status VARCHAR(75) null,requestDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table BOOKRESERVATION_RefundRequest";

	public static final String ORDER_BY_JPQL =
		" ORDER BY refundRequest.requestId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY BOOKRESERVATION_RefundRequest.requestId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long REQUESTID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public RefundRequestModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _requestId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRequestId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _requestId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RefundRequest.class;
	}

	@Override
	public String getModelClassName() {
		return RefundRequest.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<RefundRequest, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<RefundRequest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RefundRequest, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((RefundRequest)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<RefundRequest, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<RefundRequest, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(RefundRequest)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<RefundRequest, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<RefundRequest, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<RefundRequest, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<RefundRequest, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<RefundRequest, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<RefundRequest, Object>>();
		Map<String, BiConsumer<RefundRequest, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<RefundRequest, ?>>();

		attributeGetterFunctions.put("requestId", RefundRequest::getRequestId);
		attributeSetterBiConsumers.put(
			"requestId",
			(BiConsumer<RefundRequest, Long>)RefundRequest::setRequestId);
		attributeGetterFunctions.put("bookingId", RefundRequest::getBookingId);
		attributeSetterBiConsumers.put(
			"bookingId",
			(BiConsumer<RefundRequest, Long>)RefundRequest::setBookingId);
		attributeGetterFunctions.put("reason", RefundRequest::getReason);
		attributeSetterBiConsumers.put(
			"reason",
			(BiConsumer<RefundRequest, String>)RefundRequest::setReason);
		attributeGetterFunctions.put("status", RefundRequest::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<RefundRequest, String>)RefundRequest::setStatus);
		attributeGetterFunctions.put(
			"requestDate", RefundRequest::getRequestDate);
		attributeSetterBiConsumers.put(
			"requestDate",
			(BiConsumer<RefundRequest, Date>)RefundRequest::setRequestDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getRequestId() {
		return _requestId;
	}

	@Override
	public void setRequestId(long requestId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_requestId = requestId;
	}

	@Override
	public long getBookingId() {
		return _bookingId;
	}

	@Override
	public void setBookingId(long bookingId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_bookingId = bookingId;
	}

	@Override
	public String getReason() {
		if (_reason == null) {
			return "";
		}
		else {
			return _reason;
		}
	}

	@Override
	public void setReason(String reason) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_reason = reason;
	}

	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@Override
	public Date getRequestDate() {
		return _requestDate;
	}

	@Override
	public void setRequestDate(Date requestDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_requestDate = requestDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, RefundRequest.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RefundRequest toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, RefundRequest>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RefundRequestImpl refundRequestImpl = new RefundRequestImpl();

		refundRequestImpl.setRequestId(getRequestId());
		refundRequestImpl.setBookingId(getBookingId());
		refundRequestImpl.setReason(getReason());
		refundRequestImpl.setStatus(getStatus());
		refundRequestImpl.setRequestDate(getRequestDate());

		refundRequestImpl.resetOriginalValues();

		return refundRequestImpl;
	}

	@Override
	public RefundRequest cloneWithOriginalValues() {
		RefundRequestImpl refundRequestImpl = new RefundRequestImpl();

		refundRequestImpl.setRequestId(
			this.<Long>getColumnOriginalValue("requestId"));
		refundRequestImpl.setBookingId(
			this.<Long>getColumnOriginalValue("bookingId"));
		refundRequestImpl.setReason(
			this.<String>getColumnOriginalValue("reason"));
		refundRequestImpl.setStatus(
			this.<String>getColumnOriginalValue("status"));
		refundRequestImpl.setRequestDate(
			this.<Date>getColumnOriginalValue("requestDate"));

		return refundRequestImpl;
	}

	@Override
	public int compareTo(RefundRequest refundRequest) {
		long primaryKey = refundRequest.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof RefundRequest)) {
			return false;
		}

		RefundRequest refundRequest = (RefundRequest)object;

		long primaryKey = refundRequest.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<RefundRequest> toCacheModel() {
		RefundRequestCacheModel refundRequestCacheModel =
			new RefundRequestCacheModel();

		refundRequestCacheModel.requestId = getRequestId();

		refundRequestCacheModel.bookingId = getBookingId();

		refundRequestCacheModel.reason = getReason();

		String reason = refundRequestCacheModel.reason;

		if ((reason != null) && (reason.length() == 0)) {
			refundRequestCacheModel.reason = null;
		}

		refundRequestCacheModel.status = getStatus();

		String status = refundRequestCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			refundRequestCacheModel.status = null;
		}

		Date requestDate = getRequestDate();

		if (requestDate != null) {
			refundRequestCacheModel.requestDate = requestDate.getTime();
		}
		else {
			refundRequestCacheModel.requestDate = Long.MIN_VALUE;
		}

		return refundRequestCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<RefundRequest, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<RefundRequest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RefundRequest, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((RefundRequest)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, RefundRequest>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					RefundRequest.class, ModelWrapper.class);

	}

	private long _requestId;
	private long _bookingId;
	private String _reason;
	private String _status;
	private Date _requestDate;

	public <T> T getColumnValue(String columnName) {
		Function<RefundRequest, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((RefundRequest)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("requestId", _requestId);
		_columnOriginalValues.put("bookingId", _bookingId);
		_columnOriginalValues.put("reason", _reason);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("requestDate", _requestDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("requestId", 1L);

		columnBitmasks.put("bookingId", 2L);

		columnBitmasks.put("reason", 4L);

		columnBitmasks.put("status", 8L);

		columnBitmasks.put("requestDate", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private RefundRequest _escapedModel;

}