/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.esq.bus.reservation.slayers.model.impl;

import com.esq.bus.reservation.slayers.model.Route;
import com.esq.bus.reservation.slayers.model.RouteModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Route service. Represents a row in the &quot;BOOKRESERVATION_Route&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>RouteModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RouteImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RouteImpl
 * @generated
 */
public class RouteModelImpl extends BaseModelImpl<Route> implements RouteModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a route model instance should use the <code>Route</code> interface instead.
	 */
	public static final String TABLE_NAME = "BOOKRESERVATION_Route";

	public static final Object[][] TABLE_COLUMNS = {
		{"routeId", Types.BIGINT}, {"startLocationId", Types.BIGINT},
		{"endLocationId", Types.BIGINT}, {"distanceKm", Types.DOUBLE}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("routeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("startLocationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("endLocationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("distanceKm", Types.DOUBLE);
	}

	public static final String TABLE_SQL_CREATE =
		"create table BOOKRESERVATION_Route (routeId LONG not null primary key,startLocationId LONG,endLocationId LONG,distanceKm DOUBLE)";

	public static final String TABLE_SQL_DROP =
		"drop table BOOKRESERVATION_Route";

	public static final String ORDER_BY_JPQL = " ORDER BY route.routeId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY BOOKRESERVATION_Route.routeId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ROUTEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public RouteModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _routeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRouteId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _routeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Route.class;
	}

	@Override
	public String getModelClassName() {
		return Route.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Route, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Route, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Route, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Route)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Route, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Route, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Route)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Route, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Route, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Route, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Route, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Route, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Route, Object>>();
		Map<String, BiConsumer<Route, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Route, ?>>();

		attributeGetterFunctions.put("routeId", Route::getRouteId);
		attributeSetterBiConsumers.put(
			"routeId", (BiConsumer<Route, Long>)Route::setRouteId);
		attributeGetterFunctions.put(
			"startLocationId", Route::getStartLocationId);
		attributeSetterBiConsumers.put(
			"startLocationId",
			(BiConsumer<Route, Long>)Route::setStartLocationId);
		attributeGetterFunctions.put("endLocationId", Route::getEndLocationId);
		attributeSetterBiConsumers.put(
			"endLocationId", (BiConsumer<Route, Long>)Route::setEndLocationId);
		attributeGetterFunctions.put("distanceKm", Route::getDistanceKm);
		attributeSetterBiConsumers.put(
			"distanceKm", (BiConsumer<Route, Double>)Route::setDistanceKm);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getRouteId() {
		return _routeId;
	}

	@Override
	public void setRouteId(long routeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_routeId = routeId;
	}

	@Override
	public long getStartLocationId() {
		return _startLocationId;
	}

	@Override
	public void setStartLocationId(long startLocationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_startLocationId = startLocationId;
	}

	@Override
	public long getEndLocationId() {
		return _endLocationId;
	}

	@Override
	public void setEndLocationId(long endLocationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_endLocationId = endLocationId;
	}

	@Override
	public double getDistanceKm() {
		return _distanceKm;
	}

	@Override
	public void setDistanceKm(double distanceKm) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_distanceKm = distanceKm;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Route.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Route toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Route>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RouteImpl routeImpl = new RouteImpl();

		routeImpl.setRouteId(getRouteId());
		routeImpl.setStartLocationId(getStartLocationId());
		routeImpl.setEndLocationId(getEndLocationId());
		routeImpl.setDistanceKm(getDistanceKm());

		routeImpl.resetOriginalValues();

		return routeImpl;
	}

	@Override
	public Route cloneWithOriginalValues() {
		RouteImpl routeImpl = new RouteImpl();

		routeImpl.setRouteId(this.<Long>getColumnOriginalValue("routeId"));
		routeImpl.setStartLocationId(
			this.<Long>getColumnOriginalValue("startLocationId"));
		routeImpl.setEndLocationId(
			this.<Long>getColumnOriginalValue("endLocationId"));
		routeImpl.setDistanceKm(
			this.<Double>getColumnOriginalValue("distanceKm"));

		return routeImpl;
	}

	@Override
	public int compareTo(Route route) {
		long primaryKey = route.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Route)) {
			return false;
		}

		Route route = (Route)object;

		long primaryKey = route.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Route> toCacheModel() {
		RouteCacheModel routeCacheModel = new RouteCacheModel();

		routeCacheModel.routeId = getRouteId();

		routeCacheModel.startLocationId = getStartLocationId();

		routeCacheModel.endLocationId = getEndLocationId();

		routeCacheModel.distanceKm = getDistanceKm();

		return routeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Route, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Route, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Route, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Route)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Route>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Route.class, ModelWrapper.class);

	}

	private long _routeId;
	private long _startLocationId;
	private long _endLocationId;
	private double _distanceKm;

	public <T> T getColumnValue(String columnName) {
		Function<Route, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Route)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("routeId", _routeId);
		_columnOriginalValues.put("startLocationId", _startLocationId);
		_columnOriginalValues.put("endLocationId", _endLocationId);
		_columnOriginalValues.put("distanceKm", _distanceKm);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("routeId", 1L);

		columnBitmasks.put("startLocationId", 2L);

		columnBitmasks.put("endLocationId", 4L);

		columnBitmasks.put("distanceKm", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Route _escapedModel;

}