/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.esq.bus.reservation.slayers.model.impl;

import com.esq.bus.reservation.slayers.model.Seat;
import com.esq.bus.reservation.slayers.model.SeatModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Seat service. Represents a row in the &quot;BOOKRESERVATION_Seat&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SeatModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SeatImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SeatImpl
 * @generated
 */
public class SeatModelImpl extends BaseModelImpl<Seat> implements SeatModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a seat model instance should use the <code>Seat</code> interface instead.
	 */
	public static final String TABLE_NAME = "BOOKRESERVATION_Seat";

	public static final Object[][] TABLE_COLUMNS = {
		{"seatId", Types.BIGINT}, {"scheduleId", Types.BIGINT},
		{"seatNumber", Types.VARCHAR}, {"isBooked", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("seatId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("scheduleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("seatNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("isBooked", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table BOOKRESERVATION_Seat (seatId LONG not null primary key,scheduleId LONG,seatNumber VARCHAR(75) null,isBooked BOOLEAN)";

	public static final String TABLE_SQL_DROP =
		"drop table BOOKRESERVATION_Seat";

	public static final String ORDER_BY_JPQL = " ORDER BY seat.seatId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY BOOKRESERVATION_Seat.seatId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SCHEDULEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SEATID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public SeatModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _seatId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSeatId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _seatId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Seat.class;
	}

	@Override
	public String getModelClassName() {
		return Seat.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Seat, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Seat, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Seat, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Seat)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Seat, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Seat, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Seat)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Seat, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Seat, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Seat, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Seat, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Seat, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Seat, Object>>();
		Map<String, BiConsumer<Seat, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Seat, ?>>();

		attributeGetterFunctions.put("seatId", Seat::getSeatId);
		attributeSetterBiConsumers.put(
			"seatId", (BiConsumer<Seat, Long>)Seat::setSeatId);
		attributeGetterFunctions.put("scheduleId", Seat::getScheduleId);
		attributeSetterBiConsumers.put(
			"scheduleId", (BiConsumer<Seat, Long>)Seat::setScheduleId);
		attributeGetterFunctions.put("seatNumber", Seat::getSeatNumber);
		attributeSetterBiConsumers.put(
			"seatNumber", (BiConsumer<Seat, String>)Seat::setSeatNumber);
		attributeGetterFunctions.put("isBooked", Seat::getIsBooked);
		attributeSetterBiConsumers.put(
			"isBooked", (BiConsumer<Seat, Boolean>)Seat::setIsBooked);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getSeatId() {
		return _seatId;
	}

	@Override
	public void setSeatId(long seatId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_seatId = seatId;
	}

	@Override
	public long getScheduleId() {
		return _scheduleId;
	}

	@Override
	public void setScheduleId(long scheduleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_scheduleId = scheduleId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalScheduleId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("scheduleId"));
	}

	@Override
	public String getSeatNumber() {
		if (_seatNumber == null) {
			return "";
		}
		else {
			return _seatNumber;
		}
	}

	@Override
	public void setSeatNumber(String seatNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_seatNumber = seatNumber;
	}

	@Override
	public boolean getIsBooked() {
		return _isBooked;
	}

	@Override
	public boolean isIsBooked() {
		return _isBooked;
	}

	@Override
	public void setIsBooked(boolean isBooked) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isBooked = isBooked;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Seat.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Seat toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Seat>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SeatImpl seatImpl = new SeatImpl();

		seatImpl.setSeatId(getSeatId());
		seatImpl.setScheduleId(getScheduleId());
		seatImpl.setSeatNumber(getSeatNumber());
		seatImpl.setIsBooked(isIsBooked());

		seatImpl.resetOriginalValues();

		return seatImpl;
	}

	@Override
	public Seat cloneWithOriginalValues() {
		SeatImpl seatImpl = new SeatImpl();

		seatImpl.setSeatId(this.<Long>getColumnOriginalValue("seatId"));
		seatImpl.setScheduleId(this.<Long>getColumnOriginalValue("scheduleId"));
		seatImpl.setSeatNumber(
			this.<String>getColumnOriginalValue("seatNumber"));
		seatImpl.setIsBooked(this.<Boolean>getColumnOriginalValue("isBooked"));

		return seatImpl;
	}

	@Override
	public int compareTo(Seat seat) {
		long primaryKey = seat.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Seat)) {
			return false;
		}

		Seat seat = (Seat)object;

		long primaryKey = seat.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Seat> toCacheModel() {
		SeatCacheModel seatCacheModel = new SeatCacheModel();

		seatCacheModel.seatId = getSeatId();

		seatCacheModel.scheduleId = getScheduleId();

		seatCacheModel.seatNumber = getSeatNumber();

		String seatNumber = seatCacheModel.seatNumber;

		if ((seatNumber != null) && (seatNumber.length() == 0)) {
			seatCacheModel.seatNumber = null;
		}

		seatCacheModel.isBooked = isIsBooked();

		return seatCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Seat, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Seat, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Seat, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Seat)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Seat>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Seat.class, ModelWrapper.class);

	}

	private long _seatId;
	private long _scheduleId;
	private String _seatNumber;
	private boolean _isBooked;

	public <T> T getColumnValue(String columnName) {
		Function<Seat, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Seat)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("seatId", _seatId);
		_columnOriginalValues.put("scheduleId", _scheduleId);
		_columnOriginalValues.put("seatNumber", _seatNumber);
		_columnOriginalValues.put("isBooked", _isBooked);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("seatId", 1L);

		columnBitmasks.put("scheduleId", 2L);

		columnBitmasks.put("seatNumber", 4L);

		columnBitmasks.put("isBooked", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Seat _escapedModel;

}