/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.esq.bus.reservation.slayers.model.impl;

import com.esq.bus.reservation.slayers.model.SupportTicket;
import com.esq.bus.reservation.slayers.model.SupportTicketModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SupportTicket service. Represents a row in the &quot;BOOKRESERVATION_SupportTicket&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SupportTicketModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SupportTicketImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SupportTicketImpl
 * @generated
 */
public class SupportTicketModelImpl
	extends BaseModelImpl<SupportTicket> implements SupportTicketModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a support ticket model instance should use the <code>SupportTicket</code> interface instead.
	 */
	public static final String TABLE_NAME = "BOOKRESERVATION_SupportTicket";

	public static final Object[][] TABLE_COLUMNS = {
		{"supportTicketId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"subject", Types.VARCHAR}, {"message", Types.VARCHAR},
		{"status", Types.VARCHAR}, {"createdDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("supportTicketId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("subject", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("message", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createdDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table BOOKRESERVATION_SupportTicket (supportTicketId LONG not null primary key,userId LONG,subject VARCHAR(75) null,message VARCHAR(75) null,status VARCHAR(75) null,createdDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table BOOKRESERVATION_SupportTicket";

	public static final String ORDER_BY_JPQL =
		" ORDER BY supportTicket.supportTicketId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY BOOKRESERVATION_SupportTicket.supportTicketId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SUPPORTTICKETID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public SupportTicketModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _supportTicketId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSupportTicketId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _supportTicketId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SupportTicket.class;
	}

	@Override
	public String getModelClassName() {
		return SupportTicket.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SupportTicket, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SupportTicket, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SupportTicket, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((SupportTicket)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SupportTicket, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SupportTicket, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SupportTicket)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SupportTicket, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SupportTicket, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<SupportTicket, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<SupportTicket, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<SupportTicket, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<SupportTicket, Object>>();
		Map<String, BiConsumer<SupportTicket, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<SupportTicket, ?>>();

		attributeGetterFunctions.put(
			"supportTicketId", SupportTicket::getSupportTicketId);
		attributeSetterBiConsumers.put(
			"supportTicketId",
			(BiConsumer<SupportTicket, Long>)SupportTicket::setSupportTicketId);
		attributeGetterFunctions.put("userId", SupportTicket::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<SupportTicket, Long>)SupportTicket::setUserId);
		attributeGetterFunctions.put("subject", SupportTicket::getSubject);
		attributeSetterBiConsumers.put(
			"subject",
			(BiConsumer<SupportTicket, String>)SupportTicket::setSubject);
		attributeGetterFunctions.put("message", SupportTicket::getMessage);
		attributeSetterBiConsumers.put(
			"message",
			(BiConsumer<SupportTicket, String>)SupportTicket::setMessage);
		attributeGetterFunctions.put("status", SupportTicket::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<SupportTicket, String>)SupportTicket::setStatus);
		attributeGetterFunctions.put(
			"createdDate", SupportTicket::getCreatedDate);
		attributeSetterBiConsumers.put(
			"createdDate",
			(BiConsumer<SupportTicket, Date>)SupportTicket::setCreatedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getSupportTicketId() {
		return _supportTicketId;
	}

	@Override
	public void setSupportTicketId(long supportTicketId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_supportTicketId = supportTicketId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getSubject() {
		if (_subject == null) {
			return "";
		}
		else {
			return _subject;
		}
	}

	@Override
	public void setSubject(String subject) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_subject = subject;
	}

	@Override
	public String getMessage() {
		if (_message == null) {
			return "";
		}
		else {
			return _message;
		}
	}

	@Override
	public void setMessage(String message) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_message = message;
	}

	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdDate = createdDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, SupportTicket.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SupportTicket toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SupportTicket>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SupportTicketImpl supportTicketImpl = new SupportTicketImpl();

		supportTicketImpl.setSupportTicketId(getSupportTicketId());
		supportTicketImpl.setUserId(getUserId());
		supportTicketImpl.setSubject(getSubject());
		supportTicketImpl.setMessage(getMessage());
		supportTicketImpl.setStatus(getStatus());
		supportTicketImpl.setCreatedDate(getCreatedDate());

		supportTicketImpl.resetOriginalValues();

		return supportTicketImpl;
	}

	@Override
	public SupportTicket cloneWithOriginalValues() {
		SupportTicketImpl supportTicketImpl = new SupportTicketImpl();

		supportTicketImpl.setSupportTicketId(
			this.<Long>getColumnOriginalValue("supportTicketId"));
		supportTicketImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		supportTicketImpl.setSubject(
			this.<String>getColumnOriginalValue("subject"));
		supportTicketImpl.setMessage(
			this.<String>getColumnOriginalValue("message"));
		supportTicketImpl.setStatus(
			this.<String>getColumnOriginalValue("status"));
		supportTicketImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("createdDate"));

		return supportTicketImpl;
	}

	@Override
	public int compareTo(SupportTicket supportTicket) {
		long primaryKey = supportTicket.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SupportTicket)) {
			return false;
		}

		SupportTicket supportTicket = (SupportTicket)object;

		long primaryKey = supportTicket.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SupportTicket> toCacheModel() {
		SupportTicketCacheModel supportTicketCacheModel =
			new SupportTicketCacheModel();

		supportTicketCacheModel.supportTicketId = getSupportTicketId();

		supportTicketCacheModel.userId = getUserId();

		supportTicketCacheModel.subject = getSubject();

		String subject = supportTicketCacheModel.subject;

		if ((subject != null) && (subject.length() == 0)) {
			supportTicketCacheModel.subject = null;
		}

		supportTicketCacheModel.message = getMessage();

		String message = supportTicketCacheModel.message;

		if ((message != null) && (message.length() == 0)) {
			supportTicketCacheModel.message = null;
		}

		supportTicketCacheModel.status = getStatus();

		String status = supportTicketCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			supportTicketCacheModel.status = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			supportTicketCacheModel.createdDate = createdDate.getTime();
		}
		else {
			supportTicketCacheModel.createdDate = Long.MIN_VALUE;
		}

		return supportTicketCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SupportTicket, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SupportTicket, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SupportTicket, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((SupportTicket)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SupportTicket>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					SupportTicket.class, ModelWrapper.class);

	}

	private long _supportTicketId;
	private long _userId;
	private String _subject;
	private String _message;
	private String _status;
	private Date _createdDate;

	public <T> T getColumnValue(String columnName) {
		Function<SupportTicket, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SupportTicket)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("supportTicketId", _supportTicketId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("subject", _subject);
		_columnOriginalValues.put("message", _message);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("createdDate", _createdDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("supportTicketId", 1L);

		columnBitmasks.put("userId", 2L);

		columnBitmasks.put("subject", 4L);

		columnBitmasks.put("message", 8L);

		columnBitmasks.put("status", 16L);

		columnBitmasks.put("createdDate", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SupportTicket _escapedModel;

}