/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.esq.bus.reservation.slayers.model.impl;

import com.esq.bus.reservation.slayers.model.TransactionLog;
import com.esq.bus.reservation.slayers.model.TransactionLogModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TransactionLog service. Represents a row in the &quot;BOOKRESERVATION_TransactionLog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TransactionLogModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TransactionLogImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TransactionLogImpl
 * @generated
 */
public class TransactionLogModelImpl
	extends BaseModelImpl<TransactionLog> implements TransactionLogModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a transaction log model instance should use the <code>TransactionLog</code> interface instead.
	 */
	public static final String TABLE_NAME = "BOOKRESERVATION_TransactionLog";

	public static final Object[][] TABLE_COLUMNS = {
		{"logId", Types.BIGINT}, {"action", Types.VARCHAR},
		{"timestamp", Types.TIMESTAMP}, {"userId", Types.BIGINT},
		{"bookingId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("logId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("action", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("timestamp", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("bookingId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table BOOKRESERVATION_TransactionLog (logId LONG not null primary key,action VARCHAR(75) null,timestamp DATE null,userId LONG,bookingId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table BOOKRESERVATION_TransactionLog";

	public static final String ORDER_BY_JPQL =
		" ORDER BY transactionLog.logId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY BOOKRESERVATION_TransactionLog.logId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LOGID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public TransactionLogModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _logId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLogId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _logId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TransactionLog.class;
	}

	@Override
	public String getModelClassName() {
		return TransactionLog.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TransactionLog, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TransactionLog, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TransactionLog, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((TransactionLog)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TransactionLog, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TransactionLog, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TransactionLog)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TransactionLog, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TransactionLog, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<TransactionLog, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TransactionLog, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TransactionLog, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<TransactionLog, Object>>();
		Map<String, BiConsumer<TransactionLog, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<TransactionLog, ?>>();

		attributeGetterFunctions.put("logId", TransactionLog::getLogId);
		attributeSetterBiConsumers.put(
			"logId",
			(BiConsumer<TransactionLog, Long>)TransactionLog::setLogId);
		attributeGetterFunctions.put("action", TransactionLog::getAction);
		attributeSetterBiConsumers.put(
			"action",
			(BiConsumer<TransactionLog, String>)TransactionLog::setAction);
		attributeGetterFunctions.put("timestamp", TransactionLog::getTimestamp);
		attributeSetterBiConsumers.put(
			"timestamp",
			(BiConsumer<TransactionLog, Date>)TransactionLog::setTimestamp);
		attributeGetterFunctions.put("userId", TransactionLog::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<TransactionLog, Long>)TransactionLog::setUserId);
		attributeGetterFunctions.put("bookingId", TransactionLog::getBookingId);
		attributeSetterBiConsumers.put(
			"bookingId",
			(BiConsumer<TransactionLog, Long>)TransactionLog::setBookingId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getLogId() {
		return _logId;
	}

	@Override
	public void setLogId(long logId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_logId = logId;
	}

	@Override
	public String getAction() {
		if (_action == null) {
			return "";
		}
		else {
			return _action;
		}
	}

	@Override
	public void setAction(String action) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_action = action;
	}

	@Override
	public Date getTimestamp() {
		return _timestamp;
	}

	@Override
	public void setTimestamp(Date timestamp) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_timestamp = timestamp;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public long getBookingId() {
		return _bookingId;
	}

	@Override
	public void setBookingId(long bookingId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_bookingId = bookingId;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, TransactionLog.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TransactionLog toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TransactionLog>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TransactionLogImpl transactionLogImpl = new TransactionLogImpl();

		transactionLogImpl.setLogId(getLogId());
		transactionLogImpl.setAction(getAction());
		transactionLogImpl.setTimestamp(getTimestamp());
		transactionLogImpl.setUserId(getUserId());
		transactionLogImpl.setBookingId(getBookingId());

		transactionLogImpl.resetOriginalValues();

		return transactionLogImpl;
	}

	@Override
	public TransactionLog cloneWithOriginalValues() {
		TransactionLogImpl transactionLogImpl = new TransactionLogImpl();

		transactionLogImpl.setLogId(this.<Long>getColumnOriginalValue("logId"));
		transactionLogImpl.setAction(
			this.<String>getColumnOriginalValue("action"));
		transactionLogImpl.setTimestamp(
			this.<Date>getColumnOriginalValue("timestamp"));
		transactionLogImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		transactionLogImpl.setBookingId(
			this.<Long>getColumnOriginalValue("bookingId"));

		return transactionLogImpl;
	}

	@Override
	public int compareTo(TransactionLog transactionLog) {
		long primaryKey = transactionLog.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TransactionLog)) {
			return false;
		}

		TransactionLog transactionLog = (TransactionLog)object;

		long primaryKey = transactionLog.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<TransactionLog> toCacheModel() {
		TransactionLogCacheModel transactionLogCacheModel =
			new TransactionLogCacheModel();

		transactionLogCacheModel.logId = getLogId();

		transactionLogCacheModel.action = getAction();

		String action = transactionLogCacheModel.action;

		if ((action != null) && (action.length() == 0)) {
			transactionLogCacheModel.action = null;
		}

		Date timestamp = getTimestamp();

		if (timestamp != null) {
			transactionLogCacheModel.timestamp = timestamp.getTime();
		}
		else {
			transactionLogCacheModel.timestamp = Long.MIN_VALUE;
		}

		transactionLogCacheModel.userId = getUserId();

		transactionLogCacheModel.bookingId = getBookingId();

		return transactionLogCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TransactionLog, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TransactionLog, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TransactionLog, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((TransactionLog)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TransactionLog>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					TransactionLog.class, ModelWrapper.class);

	}

	private long _logId;
	private String _action;
	private Date _timestamp;
	private long _userId;
	private long _bookingId;

	public <T> T getColumnValue(String columnName) {
		Function<TransactionLog, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((TransactionLog)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("logId", _logId);
		_columnOriginalValues.put("action", _action);
		_columnOriginalValues.put("timestamp", _timestamp);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("bookingId", _bookingId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("logId", 1L);

		columnBitmasks.put("action", 2L);

		columnBitmasks.put("timestamp", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("bookingId", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private TransactionLog _escapedModel;

}