/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package EsquareEmployee_Slayer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Employees service. Represents a row in the &quot;esquare_Employees&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>EsquareEmployee_Slayer.model.impl.EmployeesModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>EsquareEmployee_Slayer.model.impl.EmployeesImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Employees
 * @generated
 */
@ProviderType
public interface EmployeesModel
	extends BaseModel<Employees>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employees model instance should use the {@link Employees} interface instead.
	 */

	/**
	 * Returns the primary key of this employees.
	 *
	 * @return the primary key of this employees
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employees.
	 *
	 * @param primaryKey the primary key of this employees
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this employees.
	 *
	 * @return the uuid of this employees
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this employees.
	 *
	 * @param uuid the uuid of this employees
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the employee ID of this employees.
	 *
	 * @return the employee ID of this employees
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this employees.
	 *
	 * @param employeeId the employee ID of this employees
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the group ID of this employees.
	 *
	 * @return the group ID of this employees
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this employees.
	 *
	 * @param groupId the group ID of this employees
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this employees.
	 *
	 * @return the company ID of this employees
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this employees.
	 *
	 * @param companyId the company ID of this employees
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the employee name of this employees.
	 *
	 * @return the employee name of this employees
	 */
	@AutoEscape
	public String getEmployeeName();

	/**
	 * Sets the employee name of this employees.
	 *
	 * @param employeeName the employee name of this employees
	 */
	public void setEmployeeName(String employeeName);

	/**
	 * Returns the employee mobile number of this employees.
	 *
	 * @return the employee mobile number of this employees
	 */
	@AutoEscape
	public String getEmployeeMobileNumber();

	/**
	 * Sets the employee mobile number of this employees.
	 *
	 * @param employeeMobileNumber the employee mobile number of this employees
	 */
	public void setEmployeeMobileNumber(String employeeMobileNumber);

	/**
	 * Returns the employee designation of this employees.
	 *
	 * @return the employee designation of this employees
	 */
	@AutoEscape
	public String getEmployeeDesignation();

	/**
	 * Sets the employee designation of this employees.
	 *
	 * @param employeeDesignation the employee designation of this employees
	 */
	public void setEmployeeDesignation(String employeeDesignation);

	/**
	 * Returns the employeephoto of this employees.
	 *
	 * @return the employeephoto of this employees
	 */
	@AutoEscape
	public String getEmployeephoto();

	/**
	 * Sets the employeephoto of this employees.
	 *
	 * @param employeephoto the employeephoto of this employees
	 */
	public void setEmployeephoto(String employeephoto);

	/**
	 * Returns the create date of this employees.
	 *
	 * @return the create date of this employees
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this employees.
	 *
	 * @param createDate the create date of this employees
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this employees.
	 *
	 * @return the modified date of this employees
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employees.
	 *
	 * @param modifiedDate the modified date of this employees
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public Employees cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}